# SRP On-Peak Days
- platform: workday
  name: SRP On-Peak Day
  country: US
  province: AZ
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]
  remove_holidays:
    - "New Year's Day"
    - "Memorial Day"
    - "Independence Day"
    - "Labor Day"
    - "Thanksgiving"
    - "Christmas Day"
