homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  internal_url: !secret internal_url
  external_url: !secret external_url
  customize: !include customize.yaml
  allowlist_external_dirs:
     - /config/json/


zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 30
    icon: mdi:home
  - name: Home Extended
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 2000
    passive: true
    icon: mdi:home
  - name: !secret work_name
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 500
    icon: mdi:domain
  - name: Work Extended
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 2000
    passive: true
    icon: mdi:domain


config:
conversation:
frontend:
  themes: !include_dir_merge_named themes/
system_health:


# updater:


http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy_ip_lan
    - !secret trusted_proxy_ip_iot
#  ip_ban_enabled: true
#  login_attempts_threshold: 3


recorder:
  purge_keep_days: 5
  db_url: !secret recorder_db_url


history:
  exclude:
    domains:
      - automation
      - date
      - script
      - time


logbook:
  include:
    domains:
      - automation
      - cover
      - device_tracker
      - script
      - switch


lovelace:
  mode: yaml
  resources:
    - url: /local/style.css
      type: css
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /local/dwains-theme/plugins/dwains-flexbox-card/dwains-flexbox-card.js
      type: module



influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_database
  include:
    entities:
       - sensor.average_humidity
       - sensor.average_temperature
       - sensor.dark_sky_humidity
       - sensor.dark_sky_precip_probability
       - sensor.dark_sky_temperature
       - sensor.den_multisensor_luminance
       - sensor.den_multisensor_relative_humidity
       - sensor.den_multisensor_temperature
       - sensor.bedroom_closet_trisensor_luminance
       - sensor.bedroom_closet_trtisensor_relative_humidity
       - sensor.bedroom_closet_trtisensor_temperature
       - sensor.downstairs_hallway_multisensor_luminance
       - sensor.downstairs_hallway_multisensor_relative_humidity
       - sensor.downstairs_hallway_multisensor_temperature
       - sensor.garage_stairs_multisensor_luminance
       - sensor.garage_stairs_multisensor_relative_humidity
       - sensor.garage_stairs_multisensor_temperature
       - sensor.main_stairs_multisensor_luminance
       - sensor.main_stairs_multisensor_relative_humidity
       - sensor.main_stairs_multisensor_temperature
       - sensor.downstairs_thermostat_humidity
       - sensor.downstairs_thermostat_target
       - sensor.downstairs_thermostat_temperature
       - sensor.upstairs_thermostat_humidity
       - sensor.upstairs_thermostat_target
       - sensor.upstairs_thermostat_temperature
       - sensor.server_rack_ups_battery_charge


sun:


# apple_tv:
#   host: !secret media_player_apple_tv_host
#   login_id: !secret media_player_apple_tv_login_id
#   name: !secret media_player_apple_tv_name
#   credentials: !secret media_player_apple_tv_credentials


sonos:
  media_player:
    hosts:
      - !secret media_player_sonos_one_kitchen
      - !secret media_player_sonos_one_bedroom
      - !secret media_player_sonos_one_bathroom
      - !secret media_player_sonos_amp_living_room
      - !secret media_player_sonos_amp_rec_room
      - !secret media_player_sonos_one_den
      - !secret media_player_sonos_move


dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: GB
  devices:
    - device_id: !secret dyson_bedroom_device_id
      device_ip: !secret dyson_bedroom_device_ip


august:
  login_method: !secret august_login_method
  username: !secret august_username
  password: !secret august_password


neato:
  username: !secret neato_username
  password: !secret neato_password


emulated_hue:
  host_ip: !secret emulated_hue_host
  listen_port: !secret emulated_hue_port
  expose_by_default: false
  entities:
    light.rec_room_lights:
      hidden: false
    light.bedroom_lights:
      hidden: false
    light.kitchen:
      hidden: false
    light.bedroom_tiles:
      hidden: false
    light.bedroom_closet_lights:
      hidden: false
    light.bedroom_hallway:
      hidden: false
    light.den_cabinets:
      hidden: false
    light.den_hallway:
      hidden: false
    light.den_lights:
      hidden: false
    light.downstairs_hallway:
      hidden: false
    light.garage_lights:
      hidden: false
    light.garage_stairs:
      hidden: false
    light.guest_bedroom_closet_lights:
      hidden: false
    light.laundry_lights:
      hidden: false
    light.living_room:
      hidden: false
    light.main_stairs:
      hidden: false
    light.patio_lights:
      hidden: false
    light.patio_string_lights:
      hidden: false
    light.living_room_tv:
      hidden: false
    light.upstairs_hallway_group_lights:
      hidden: false
    light.upstairs_hallway:
      hidden: false
    light.rec_room_tiles:
      hidden: false
    input_boolean.mode_guest:
      hidden: false
    input_boolean.mode_home_theater:
      hidden: false
    input_boolean.mode_sleep:
      hidden: false


zwave:
  usb_path: !secret zwave_usb_path
  config_path: !secret zwave_config_path
  polling_interval: 60000
  device_config:
    light.garage_stairs:
      polling_intensity: 1
      refresh_value: true
      delay: 3
    light.downstairs_hallway:
      polling_intensity: 1
      refresh_value: true
      delay: 3
    light.living_room:
      polling_intensity: 1
      refresh_value: true
      delay: 3
    light.kitchen:
      polling_intensity: 1
      refresh_value: true
      delay: 3
    light.main_stairs:
      polling_intensity: 1
      refresh_value: true
      delay: 3
    light.upstairs_hallway:
      polling_intensity: 1
      refresh_value: true
      delay: 3
    light.bedroom_hallway:
      polling_intensity: 1
      refresh_value: true
      delay: 3
    light.den_hallway:
      polling_intensity: 1
      refresh_value: true
      delay: 3
    zwave.unknown_node_45:
      ignored: true


nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret


light:
  - platform: group
    name: Patio Lights
    entities:
      - light.patio_1
      - light.patio_2
      - light.patio_3
  - platform: group
    name: Upstairs Hallway Group Lights
    entities:
      - light.main_stairs
      - light.upstairs_hallway
      - light.bedroom_hallway
  - platform: group
    name: Bedroom Lights
    entities:
      - light.bedroom_1
      - light.bedroom_2
  - platform: group
    name: Den Cabinets
    entities:
      - light.den_cabinet_1
      - light.den_cabinet_2
  - platform: group
    name: Den Lights
    entities:
      - light.den_1
      - light.den_2
  - platform: switch
    name: Garage Lights
    entity_id: switch.garage_lights
  - platform: switch
    name: Patio String Lights
    entity_id: switch.patio_string_lights
  - platform: switch
    name: Bedroom Closet Lights
    entity_id: switch.bedroom_closet_lights
  - platform: switch
    name: Laundry Lights
    entity_id: switch.laundry_lights
  - platform: switch
    name: Guest Bedroom Closet Lights
    entity_id: switch.guest_bedroom_closet_lights


# device_tracker:
#   - platform: automatic
#     client_id: !secret automatic_client_id
#     secret: !secret automatic_secret
#     current_location: true
#     devices:
#       - 2007 Honda Element
#  - platform: owntracks
#    max_gps_accuracy: 200
#    track_new_devices: false


# mqtt:
#   broker: !secret mqtt_remote_host
#   port: !secret mqtt_remote_port
#   client_id: !secret mqtt_remote_client_id
#   keepalive: 60
#   username: !secret mqtt_remote_username
#   password: !secret mqtt_remote_password


notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key


geofency:
  mobile_beacons:
    - Octavia


google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret
  track_new_calendar: true


konnected:
  access_token: !secret konnected_access_token
  api_host: !secret konnected_api_host
  devices:
    - id: !secret konnected_main_device_id
      host: !secret konnected_main_host
      port: !secret konnected_main_port
      discovery: false
      binary_sensors:
        - zone: 1
          type: motion
          name: !secret konnected_main_zone1_name
        - zone: 2
          type: door
          name: !secret konnected_main_zone2_name
        - zone: 3
          type: door
          name: !secret konnected_main_zone3_name
        - zone: 4
          type: window
          name: !secret konnected_main_zone4_name
        - zone: 5
          type: door
          name: !secret konnected_main_zone5_name
        - zone: 6
          type: window
          name: !secret konnected_main_zone6_name
    - id: !secret konnected_addon_device_id
      host: !secret konnected_addon_host
      port: !secret konnected_addon_port
      discovery: false
      binary_sensors:
        - zone: 1
          type: motion
          name: !secret konnected_addon_zone1_name
        - zone: 2
          type: window
          name: !secret konnected_addon_zone2_name
        - zone: 3
          type: window
          name: !secret konnected_addon_zone3_name
        - zone: 4
          type: door
          name: !secret konnected_addon_zone4_name
        - zone: 5
          type: window
          name: !secret konnected_addon_zone5_name
        - zone: 6
          type: window
          name: !secret konnected_addon_zone6_name


cover:
  - platform: template
    covers:
      garage_actual:
        friendly_name: "Garage Actual"
        entity_id: binary_sensor.garage_actual
        value_template: "{{ is_state('binary_sensor.garage_actual', 'on') }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garage_actual
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garage_actual
        stop_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garage_actual
        icon_template: >-
          {% if is_state('binary_sensor.garage_actual', 'on') %}
            mdi:garage-open-variant
          {% else %}
            mdi:garage-variant
          {% endif %}


homekit:
  auto_start: false
  ip_address: !secret homekit_ip_address
  filter:
    include_domains:
      - climate
      - cover
      - light
    include_entities:
      - binary_sensor.bedroom_windows
      - binary_sensor.den_door
      - binary_sensor.den_windows
      - binary_sensor.front_door
      - binary_sensor.garage_door
      - binary_sensor.guest_bedroom_windows
      - binary_sensor.kitchen_windows
      - binary_sensor.living_room_windows
      - binary_sensor.patio_door
      - binary_sensor.rec_room_windows
      - binary_sensor.den_multisensor_sensor
      - binary_sensor.bedroom_closet_trisensor_sensor
      - binary_sensor.downstairs_hallway_multisensor_sensor
      - binary_sensor.garage_motion_sensor
      - binary_sensor.garage_stairs_multisensor_sensor
      - binary_sensor.living_room_motion_sensor
      - binary_sensor.main_stairs_multisensor_sensor
      - binary_sensor.upstairs_hallway_motion_sensor
      - input_boolean.mode_guest
      - input_boolean.mode_home_theater
      - input_boolean.mode_sleep
      - remote.living_room_apple_tv
    exclude_entities:
      - light.patio_lights
      - light.rec_room_lights
      - light.den_lights
      - light.den_cabinets
      - light.bedroom_lights
      - light.main_stairs_and_upstairs_hallway


ios:
  push:
    categories:
      - name: Start Sleep Mode
        identifier: 'mode_sleep_start'
        actions:
          - identifier: 'MODE_SLEEP_ON'
            title: 'Turn On'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'
      - name: End Sleep Mode
        identifier: 'mode_sleep_end'
        actions:
          - identifier: 'MODE_SLEEP_OFF'
            title: 'Turn Off'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'
      - name: End Peloton Mode
        identifier: 'mode_peloton_end'
        actions:
          - identifier: 'MODE_PELOTON_OFF'
            title: 'Turn Off'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'
      - name: Close Garage Actual
        identifier: 'garage_actual_close'
        actions:
          - identifier: 'GARAGE_ACTUAL_CLOSE'
            title: 'Close'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'
mobile_app:


# Disabled Features ##########################################
# introduction:
# discovery:
# ssdp:
# zeroconf:
# tts:
#   platform: google



# Includes ###################################################
automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensor.yaml
group: !include group.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
media_player: !include media_player.yaml
rest_command: !include rest_command.yaml
scene: !include scene.yaml
script: !include_dir_merge_named script/
sensor: !include sensor.yaml
shell_command: !include shell_command.yaml
switch: !include switch.yaml
