##############################################################
# Media Servers
##############################################################
- platform: plex
  entity_namespace: plex
  scan_interval: 5
  name: !secret media_player_plex_name

##############################################################
# Media Players
##############################################################
- platform: apple_tv
  host: !secret media_player_apple_tv_host
  login_id: !secret media_player_apple_tv_login_id
  name: !secret media_player_apple_tv_name

##############################################################
# Receivers
##############################################################
- platform: denonavr
  host: !secret media_player_denon_desk_host
  name: !secret media_player_denon_desk_name

- platform: denon
  host: !secret media_player_denon_home_theater_host
  name: !secret media_player_denon_home_theater_name
