##############################################################
# Media Servers
##############################################################
- platform: plex
  entity_namespace: plex
  scan_interval: 5
  name: !secret media_player_plex_name

##############################################################
# Media Players
##############################################################
- platform: spotify
  client_id: !secret media_player_spotify_client_id
  client_secret: !secret media_player_spotify_client_secret

##############################################################
# Receivers
##############################################################
- platform: denonavr
  host: !secret media_player_denon_desk_host
  name: !secret media_player_denon_desk_name

- platform: denonavr
  host: !secret media_player_denon_home_theater_host
  name: !secret media_player_denon_home_theater_name
