# Kitchen ####################################################
- platform: template
  switches:
    kitchen_lights:
      friendly_name: 'Kitchen Lights'
      value_template: "{{ is_state('light.kitchen_lights', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.scene_select_by_time
        data:
          variables:
            room: kitchen
      turn_off:
        service: homeassistant.turn_off
        entity_id:
          - light.kitchen_lights
          - input_boolean.color_loop_kitchen_overhead

# Bathroom ####################################################
- platform: template
  switches:
    bathroom_lights:
      friendly_name: 'Bathroom Lights'
      value_template: "{{ is_state('light.bathroom_lights', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.scene_select_by_time
        data:
          variables:
            room: bathroom
      turn_off:
        service: homeassistant.turn_off
        entity_id: light.bathroom_lights

# Bedroom ####################################################
- platform: template
  switches:
    bedroom_lights:
      friendly_name: 'Bedroom Lights'
      value_template: "{{ is_state('light.bedroom_lights', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.scene_select_by_time
        data:
          variables:
            room: bedroom
      turn_off:
        - service: homeassistant.turn_off
          entity_id:
            - light.bedroom_lights
            - input_boolean.color_loop_bedroom

# Living Room ################################################
- platform: template
  switches:
    living_room_lights:
      friendly_name: 'Living Room Lights'
      value_template: "{{ is_state('light.living_room_lights', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.scene_select_by_time
        data:
          variables:
            room: living_room
      turn_off:
        - service: homeassistant.turn_off
          entity_id:
            - light.living_room_lights
            - input_boolean.color_loop_living_room

# Office #####################################################
- platform: template
  switches:
    office_lights:
      friendly_name: 'Office Lights'
      value_template: "{{ is_state('light.office_lights', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.scene_select_by_time
        data:
          variables:
            room: office
      turn_off:
        service: homeassistant.turn_off
        entity_id: light.office_lights


##############################################################
# Duplicated for Tablet Dashboard
##############################################################

# Kitchen ####################################################
- platform: template
  switches:
    dashboard_kitchen_lights:
      friendly_name: 'Kitchen'
      value_template: "{{ is_state('light.kitchen_lights', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.scene_select_by_time
        data:
          variables:
            room: kitchen
      turn_off:
        service: homeassistant.turn_off
        entity_id:
          - light.kitchen_lights
          - input_boolean.color_loop_kitchen_overhead

# Bathroom ####################################################
- platform: template
  switches:
    dashboard_bathroom_lights:
      friendly_name: 'Bathroom'
      value_template: "{{ is_state('light.bathroom_lights', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.scene_select_by_time
        data:
          variables:
            room: bathroom
      turn_off:
        service: homeassistant.turn_off
        entity_id: light.bathroom_lights

# Bedroom ####################################################
- platform: template
  switches:
    dashboard_bedroom_lights:
      friendly_name: 'Bedroom'
      value_template: "{{ is_state('light.bedroom_lights', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.scene_select_by_time
        data:
          variables:
            room: bedroom
      turn_off:
        - service: homeassistant.turn_off
          entity_id:
            - light.bedroom_lights
            - input_boolean.color_loop_bedroom

# Living Room ################################################
- platform: template
  switches:
    dashboard_living_room_lights:
      friendly_name: 'Living Room'
      value_template: "{{ is_state('light.living_room_lights', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.scene_select_by_time
        data:
          variables:
            room: living_room
      turn_off:
        - service: homeassistant.turn_off
          entity_id:
            - light.living_room_lights
            - input_boolean.color_loop_living_room

# Office #####################################################
- platform: template
  switches:
    dashboard_office_lights:
      friendly_name: 'Office'
      value_template: "{{ is_state('light.office_lights', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.scene_select_by_time
        data:
          variables:
            room: office
      turn_off:
        service: homeassistant.turn_off
        entity_id: light.office_lights
