title: Home Assistant
background: var(--primary-background-color)
views:
  - icon: mdi:home-assistant
    title: Home
    path: home
    theme: Tablet Dashboard
    background: center / cover no-repeat fixed url('/local/dashboard/bg.png')
    popup_cards: !include_dir_merge_named lovelace/popups/home/
    panel: true
    cards:
      - type: custom:mod-card
        card_mod:
          style: |
            ha-card {
              margin: 0 auto;
            }
        card:
          type: vertical-stack
          cards:
            - !include lovelace/partials/home/header.yaml
            - !include lovelace/partials/home/content.yaml
  - icon: mdi:lightbulb
    title: Lights
    path: lights
    theme: Tablet Dashboard
    background: center / cover no-repeat fixed url('/local/dashboard/bg.png')
    panel: true
    cards:
      - type: custom:mod-card
        card_mod:
          style: |
            ha-card {
              max-width: 1465px;
              margin: 0 auto;
            }
        card:
          type: vertical-stack
          cards:
            - !include lovelace/partials/lights/header.yaml
            - !include lovelace/partials/lights/content.yaml
  - icon: mdi:music
    title: Sonos
    path: sonos
    theme: Tablet Dashboard
    background: center / cover no-repeat fixed url('/local/dashboard/bg.png')
    panel: true
    cards:
      - type: custom:mod-card
        card_mod:
          style: |
            ha-card {
              max-width: 1465px;
              margin: 0 auto;
            }
        card:
          type: vertical-stack
          cards:
            - !include lovelace/partials/sonos/header.yaml
            - !include lovelace/partials/sonos/content.yaml
  - icon: mdi:television
    title: Home Theater
    path: home_theater
    theme: Tablet Dashboard
    background: center / cover no-repeat fixed url('/local/dashboard/bg.png')
    panel: true
    cards:
      - type: custom:mod-card
        card_mod:
          style: |
            ha-card {
              max-width: 1465px;
              margin: 0 auto;
            }
        card:
          type: vertical-stack
          cards:
            - !include lovelace/partials/home_theater/header.yaml
            - !include lovelace/partials/home_theater/content.yaml
  - icon: mdi:shield-home
    title: Security
    path: security
    theme: Tablet Dashboard
    background: center / cover no-repeat fixed url('/local/dashboard/bg.png')
    panel: true
    cards:
      - type: custom:mod-card
        card_mod:
          style: |
            ha-card {
              max-width: 1465px;
              margin: 0 auto;
            }
        card:
          type: vertical-stack
          cards:
            - !include lovelace/partials/security/header.yaml
            - !include lovelace/partials/security/content.yaml
  - icon: mdi:heart-pulse
    title: Health
    path: health
    theme: Tablet Dashboard
    background: center / cover no-repeat fixed url('/local/dashboard/bg.png')
    panel: true
    cards:
      - type: custom:mod-card
        card_mod:
          style: |
            ha-card {
              max-width: 1465px;
              margin: 0 auto;
            }
        card:
          type: vertical-stack
          cards:
            - !include lovelace/partials/health/header.yaml
            - !include lovelace/health/servers.yaml
            - !include lovelace/health/services.yaml
            - !include lovelace/health/network.yaml
            - !include lovelace/health/battery.yaml
  - icon: mdi:account-cog
    title: Preferences
    path: preferences
    theme: Tablet Dashboard
    background: center / cover no-repeat fixed url('/local/dashboard/bg.png')
    panel: true
    cards:
      - type: custom:mod-card
        card_mod:
          style: |
            ha-card {
              max-width: 1465px;
              margin: 0 auto;
            }
        card:
          type: vertical-stack
          cards:
            - !include lovelace/partials/preferences/header.yaml
            - !include lovelace/preferences/lights.yaml
            - !include lovelace/preferences/thermostat.yaml

  # Always Hidden ##############################################
  - title: Scenes
    path: scenes
    panel: true
    visible: false
    cards:
      - type: custom:mod-card
        card_mod:
          style: |
            ha-card {
              max-width: 1465px;
              margin: 0 auto;
            }
        card:
          type: vertical-stack
          cards:
            - !include lovelace/scenes/header.yaml
            - !include lovelace/scenes/scenes.yaml
  - title: Modes
    path: modes
    panel: true
    visible: false
    cards:
      - type: custom:mod-card
        style: |
          ha-card {
            max-width: 1465px;
            margin: 0 auto;
          }
        card:
          type: vertical-stack
          cards:
            - !include lovelace/modes/header.yaml
            - !include lovelace/modes/user.yaml
            - !include lovelace/modes/security.yaml
            - !include lovelace/modes/home.yaml

button_card_templates: !include_dir_merge_named lovelace/button_card_templates
