title: Home Assistant
views:
  - icon: mdi:home-assistant
    title: Home
    path: home
    cards:
      - !include lovelace/home/conditionals.yaml
      - !include lovelace/home/entities.yaml
      - !include lovelace/home/buttons.yaml
      - !include lovelace/home/streams.yaml

  - icon: mdi:lightbulb
    title: Lights
    path: lights
    cards:
      - !include lovelace/lights/conditionals.yaml
      - !include lovelace/lights/entities.yaml
  - icon: mdi:thermostat
    title: Thermostat
    path: thermostat
    cards:
      - !include lovelace/thermostat/downstairs.yaml
      - !include lovelace/thermostat/upstairs.yaml
      - !include lovelace/thermostat/entities.yaml
  - icon: mdi:music
    title: Sonos
    path: sonos
    cards:
      - !include lovelace/sonos/entities.yaml
  - icon: mdi:television
    title: Home Theater
    path: home_theater
    cards:
      - type: vertical-stack
        cards:
          - !include lovelace/home_theater/player.yaml
          - !include lovelace/home_theater/buttons.yaml
          - !include lovelace/home_theater/bandwidth.yaml
          - !include lovelace/home_theater/streams.yaml
          - !include lovelace/home_theater/users.yaml
          - !include lovelace/home_theater/sonarr.yaml
  - icon: mdi:shield-home
    title: Security
    path: security
    cards:
      - !include lovelace/security/doors.yaml
      - !include lovelace/security/windows.yaml
      - !include lovelace/security/motion.yaml
      - !include lovelace/security/modes.yaml
  - icon: mdi:heart-pulse
    title: Health
    path: health
    cards:
      - !include lovelace/health/servers.yaml
      - !include lovelace/health/services.yaml
      - !include lovelace/health/network.yaml
      - !include lovelace/health/battery.yaml
      - !include lovelace/health/zwave.yaml
  - icon: mdi:account-cog
    title: Preferences
    path: Preferences
    cards:
      - !include lovelace/preferences/lights.yaml
      - !include lovelace/preferences/thermostat.yaml
