title: Home Assistant
background: var(--primary-background-color)
views:
  - type: custom:grid-layout
    icon: mdi:home-assistant
    path: home
    title: Home
    theme: Tablet Dashboard
 #   background: center / cover no-repeat fixed url('/local/dashboard/bg-phone.png')
    popup_cards: !include_dir_merge_named lovelace/popups/home/
    layout:
      grid-template-columns: auto
      grid-template-rows: auto auto
      grid-template-areas: |
        "header"  "content"
      margin: 0
    cards:
      - !include lovelace/partials/home/header.yaml
      - !include lovelace/partials/home/content.yaml
  - type: custom:grid-layout
    icon: mdi:lightbulb
    path: lights
    title: Lights
    theme: Tablet Dashboard
    layout:
      grid-template-columns: auto
      grid-template-rows: auto auto
      grid-template-areas: |
        "header"  "content"
      margin: 0
    cards:
      - !include lovelace/partials/lights/header.yaml
      - !include lovelace/partials/lights/content.yaml
  - type: custom:grid-layout
    icon: mdi:music
    path: sonos
    title: Sonos
    theme: Tablet Dashboard
    layout:
      grid-template-columns: auto
      grid-template-rows: auto auto
      grid-template-areas: |
        "header"  "content"
      margin: 0
    cards:
      - !include lovelace/partials/sonos/header.yaml
      - !include lovelace/partials/sonos/content.yaml
  - type: custom:grid-layout
    icon: mdi:television
    path: home_theater
    title: Home Theater
    theme: Tablet Dashboard
    layout:
      grid-template-columns: auto
      grid-template-rows: auto auto
      grid-template-areas: |
        "header"  "content"
      margin: 0
    cards:
      - !include lovelace/partials/home_theater/header.yaml
      - !include lovelace/partials/home_theater/content.yaml
  - type: custom:grid-layout
    icon: mdi:shield-home
    path: security
    title: Security
    theme: Tablet Dashboard
    layout:
      grid-template-columns: auto
      grid-template-rows: auto auto
      grid-template-areas: |
        "header"  "content"
      margin: 0
    cards:
      - !include lovelace/partials/security/header.yaml
      - !include lovelace/partials/security/content.yaml
  - type: custom:grid-layout
    icon: mdi:heart-pulse
    path: health
    title: Health
    theme: Tablet Dashboard
    layout:
      grid-template-columns: auto
      grid-template-rows: auto auto
      grid-template-areas: |
        "header"  "content"
      margin: 0
    cards:
      - !include lovelace/partials/health/header.yaml
      - !include lovelace/partials/health/content.yaml
  - type: custom:grid-layout
    icon: mdi:account-cog
    path: preferences
    title: Preferences
    theme: Tablet Dashboard
    layout:
      grid-template-columns: auto
      grid-template-rows: auto auto
      grid-template-areas: |
        "header"  "content"
      margin: 0
    cards:
      - !include lovelace/partials/preferences/header.yaml
      - !include lovelace/partials/preferences/content.yaml

  # Always Hidden ##############################################
  - type: custom:grid-layout
    path: scenes
    title: Scenes
    layout:
      grid-template-columns: auto
      grid-template-rows: auto auto
      grid-template-areas: |
        "header"  "content"
      margin: 0
    visible: false
    cards:
      - !include lovelace/partials/scenes/header.yaml
      - !include lovelace/partials/scenes/scenes.yaml

button_card_templates: !include_dir_merge_named lovelace/button_card_templates
