##############################################################
# Speaker Grouping
##############################################################
# Group Master Speaker #######################################
# Sets the input_select based on the master speaker sensor

- alias: Set Sonos Group Master Input Select
  trigger:
    - platform: state
      entity_id: sensor.sonos_group_master
    - platform: homeassistant
      event: start
  condition:
    - '{{ states.sensor.sonos_group_master.state != "" }}'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.master_sonos
        option: >-
          {% set master = states('sensor.sonos_group_master') %}
          {{ 'Kitchen' if 'media_player.sonos_kitchen' in master }}
          {{ 'Living Room' if 'media_player.sonos_living_room' in master }}
          {{ 'Rec Room' if 'media_player.sonos_rec_room' in master }}
          {{ 'Bedroom' if 'media_player.sonos_bedroom' in master }}
          {{ 'Bathroom' if 'media_player.sonos_bathroom' in master }}
          {{ 'Den' if 'media_player.sonos_den' in master }}
          {{ 'Move' if 'media_player.sonos_move' in master }}

# Sync Input Booleans to Speaker Status ######################
- alias: Set Sonos Switches On
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.sonos_switches_on
    - platform: homeassistant
      event: start
  condition:
    - '{{ states("sensor.sonos_switches_on") != "" }}'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: '{{ states("sensor.sonos_switches_on") }}'
- alias: Set Sonos Switches Off
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.sonos_switches_off
    - platform: homeassistant
      event: start
  condition:
    - '{{ states("sensor.sonos_switches_off") != "" }}'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: '{{ states("sensor.sonos_switches_off") }}'

# Toggle Speaker State #######################################
- alias: Toggle Sonos Speaker State
  mode: restart
  trigger:
    - platform: state
      entity_id:
        - input_boolean.sonos_bathroom
        - input_boolean.sonos_bedroom
        - input_boolean.sonos_den
        - input_boolean.sonos_kitchen
        - input_boolean.sonos_living_room
        - input_boolean.sonos_rec_room
        - input_boolean.sonos_move
  action:
    - service: script.turn_on
      data:
        entity_id: >-
          {% set switch  = trigger.to_state.entity_id %}
          {% if is_state(switch, "on") %}
            script.sonos_speaker_join_group
          {% else %}
            script.sonos_speaker_unjoin_group
          {% endif %}
        variables:
          speaker: '{{ trigger.to_state.entity_id|replace("input_boolean", "media_player") }}'
