##############################################################
# Battery Notifications
##############################################################
# Low battery notification and task added to Things
- alias: Notify Battery - Replace Low Battery
  trigger:
    - platform: numeric_state
      entity_id: sensor.battery_august_front_door
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_august_front_door_keypad
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_august_front_door
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_august_garage_door
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_garage_stairs_multisensor
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_garage_motion_sensor
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_downstairs_hallway_multisensor
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_main_stairs_multisensor
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_bedroom_closet_door_sensor
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_laundry_door_left_sensor
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_laundry_door_right_sensor
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_den_multisensor
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_den_trisensor
      below: 50
    - platform: numeric_state
      entity_id: sensor.battery_guest_bedroom_closet_door_sensor
      below: 50
  action:
    - service: notify.mobile_app_alexs_iphone
      data_template:
        title: "Condo"
        message: "The {{ trigger.to_state.attributes.friendly_name }} battery is at {{ trigger.to_state.state }}%. A task to replace it has been added to Things."
        data:
          push:
            thread-id: "ha-condo-group"
            sound: "gesture.wav"
    - service_template: rest_command.things_add_task
      data_template:
        title: "Replace {{ trigger.to_state.attributes.friendly_name }} Battery"
        when: "Today"
        list: "Maintenance"
