##############################################################
# General Events
##############################################################
# Windows Notifications ######################################
- alias: Notify Security - Window Opened or Closed When Away
  mode: queued
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kitchen_windows
        - binary_sensor.kitchen_windows
        - binary_sensor.living_room_windows
        - binary_sensor.living_room_windows
        - binary_sensor.rec_room_windows
        - binary_sensor.rec_room_windows
        - binary_sensor.bedroom_windows
        - binary_sensor.bedroom_windows
        - binary_sensor.den_windows
        - binary_sensor.den_windows
        - binary_sensor.guest_bedroom_windows
        - binary_sensor.guest_bedroom_windows
      to: 'off'
  condition:
    - condition: state
      entity_id: group.residents
      state: 'not_home'
  action:
    - service: notify.mobile_app_alexs_iphone
      data:
        title: "Condo"
        message: "The {{ trigger.to_state.attributes.friendly_name }} were {% if trigger.to_state.state == 'on' %}opened{% else %}closed{% endif %}."
        data:
          push:
            thread-id: "ha-condo-group"
            sound: "gamelan.wav"

# Door Notifications #########################################
- alias: Notify Security - Door Opened
  mode: queued
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.garage_door
        - binary_sensor.front_door
        - binary_sensor.patio_door
        - binary_sensor.den_door
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.mode_sleep
      state: 'off'
  action:
    - service: notify.mobile_app_alexs_iphone
      data:
        title: "Condo"
        message: "The {{ trigger.to_state.attributes.friendly_name }} was {% if trigger.to_state.state == 'on' %}opened{% else %}closed{% endif %}."
        data:
          push:
            thread-id: "ha-condo-group"
            sound: "gamelan.wav"

# Lock Notifications #########################################
# - alias: Notify Security - Front Door Locked or Unlocked
#   trigger:
#     - platform: state
#       entity_id: lock.august_web_front_door
#       from: 'locked'
#       to: 'unlocked'
#     - platform: state
#       entity_id: lock.august_web_front_door
#       from: 'unlocked'
#       to: 'locked'
#   action:
#     - wait_for_trigger:
#         - platform: state
#           entity_id: sensor.august_web_front_door_operator
#       timeout:
#         seconds: 20
#     - service: notify.mobile_app_alexs_iphone
#       data:
#         title: "Condo"
#         message: >-
#           {% if is_state('sensor.august_web_front_door_operator', 'Manual Lock') or is_state('sensor.august_web_front_door_operator', 'Manual Unlock') %}
#             {% set message = 'manually ' ~ states('lock.august_web_front_door') %}
#           {% else %}
#             {% set message = states('lock.august_web_front_door') ~ ' by ' ~ states('sensor.august_web_front_door_operator') %}
#           {% endif %}
#           The Front Door was {{ message }}.
#         data:
#           push:
#             thread-id: "ha-condo-group"
#             sound: "gamelan.wav"

# Garage Notifications #######################################
- alias: Notify Security - Garage Actual Opened or Closed
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.garage_actual
      from: 'closed'
      to: 'open'
    - platform: state
      entity_id:  sensor.garage_actual
      from: 'open'
      to: 'closed'
  condition:
    - condition: state
      entity_id: input_boolean.mode_sleep
      state: 'off'
  action:
    - service: notify.mobile_app_alexs_iphone
      data:
        title: "Condo"
        message: "The {{ trigger.to_state.attributes.friendly_name }} was {% if trigger.to_state.state == 'open' %}opened{% else %}closed{% endif %}."
        data:
          push:
            thread-id: "ha-condo-group"
            sound: "gamelan.wav"

# Motion Notifications #######################################
# - alias: Notify Security - Front Door Motion
#   trigger:
#     - platform: state
#       entity_id: input_boolean.motion_front_door
#       to: 'on'
#   condition:
#     - condition: state
#       entity_id: group.residents
#       state: 'home'
#   action:
#     - service: notify.mobile_app_alexs_iphone
#       data:
#         title: "Condo"
#         message: "Motion detected at the the Front Door."
#         data:
#           push:
#             thread-id: "ha-condo-group"
#             sound: "silent.wav"


##############################################################
# Extended Time Events
##############################################################
# Door Notifications #########################################
- alias: Notify Security - Door Opened for Extended Period of Time
  mode: queued
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.garage_door
        - binary_sensor.front_door
        - binary_sensor.patio_door
        - binary_sensor.den_door
      to: 'on'
      for:
        minutes: 2
    - platform: state
      entity_id:
        - binary_sensor.garage_door
        - binary_sensor.front_door
        - binary_sensor.patio_door
        - binary_sensor.den_door
      to: 'on'
      for:
        minutes: 5
    - platform: state
      entity_id:
        - binary_sensor.garage_door
        - binary_sensor.front_door
        - binary_sensor.patio_door
        - binary_sensor.den_door
      to: 'on'
      for:
        minutes: 10
  action:
    - service: notify.mobile_app_alexs_iphone
      data:
        title: "Condo"
        message: "The {{ trigger.to_state.attributes.friendly_name }} has been open for {{ (trigger.for.total_seconds() / 60) | int(0) }} minutes."
        data:
          push:
            thread-id: "ha-condo-group"
            sound: "siren.wav"

# Garage Notifications #######################################
- alias: Notify Security - Garage Actual Opened for Extended Period of Time
  mode: queued
  trigger:
    - platform: state
      entity_id:  sensor.garage_actual
      to: 'open'
      for:
        minutes: 10
    - platform: state
      entity_id:  sensor.garage_actual
      to: 'open'
      for:
        minutes: 20
    - platform: state
      entity_id:  sensor.garage_actual
      to: 'open'
      for:
        minutes: 30
  action:
    service: notify.mobile_app_alexs_iphone
    data:
      title: "Condo"
      message: "The {{ trigger.to_state.attributes.friendly_name }} has been open for {{ (trigger.for.total_seconds() / 60) | int(0) }} minutes."
      data:
        push:
          thread-id: "ha-condo-group"
          sound: "siren.wav"

##############################################################
# Guest Mode
##############################################################
- alias: Notify of Guest Motion Detected
  mode: queued
  trigger:
    - platform: state
      entity_id: input_boolean.mode_guest
      to: 'on'
  action:
    - delay: '00:00:02'
    - service: notify.mobile_app_alexs_iphone
      data:
        title: "Condo"
        message: >-
          {%- if is_state("lock.august_web_front_door", "unlocked") -%}
            Guest Mode has been triggered and the front door was {% if is_state("sensor.august_smart_lock_pro_front_door_access_control", "2") %}manually unlocked.{% elif is_state("sensor.august_smart_lock_pro_front_door_access_control", "4") %}unlocked with the August app.{% elif is_state("sensor.august_smart_lock_pro_front_door_access_control", "6") %}unlocked with the keypad.{% else %}unlocked.{% endif %} Expecting anyone?
          {%- else -%}
            Guest Mode has been triggered and the front door is locked. Cats? Aliens?
          {%- endif %}
        data:
          push:
            thread-id: "ha-condo-group"
            sound: "siren.wav"

- alias: Notify of Guest Mode Ended
  mode: queued
  trigger:
    - platform: state
      entity_id: input_boolean.mode_guest
      to: 'off'
  condition:
    - condition: state
      entity_id: group.residents
      state: 'not_home'
  action:
    - service: notify.mobile_app_alexs_iphone
      data:
        title: "Condo"
        message: "Motion in guest areas has not been detected for 30 minutes. Guest Mode has been turned off."
        data:
          push:
            thread-id: "ha-condo-group"
            sound: "gamelan.wav"


##############################################################
# Critical Events
##############################################################
# Home Notifications #########################################
- alias: Notify Security - Home Not Secure for Extended Period of Time When Away
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.dashboard_home_state
      to: "Insecure"
      for:
        minutes: 10
    - platform: state
      entity_id: group.residents
      to: 'not_home'
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dashboard_home_state
        state: 'Insecure'
      - condition: state
        entity_id: group.residents
        state: 'not_home'
  action:
    service: notify.mobile_app_alexs_iphone
    data:
      title: "Condo"
      message: "The condo has not been secure for 10 minutes."
      data:
        push:
          thread-id: "ha-condo-group"
          sound:
            name: "siren.wav"
            critical: 1
            volume: 1.0

# Sleep Mode Notifications ###################################
- alias: Notify Security - Home Not Secure During Sleep Mode
  mode: queued
  trigger:
    - platform: state
      entity_id:  sensor.garage_actual
      to: 'open'
    - platform: state
      entity_id:
        - binary_sensor.garage_door
        - binary_sensor.front_door
        - binary_sensor.patio_door
        - binary_sensor.den_door
        - binary_sensor.kitchen_windows
        - binary_sensor.living_room_windows
        - binary_sensor.rec_room_windows
        - binary_sensor.bedroom_windows
        - binary_sensor.den_windows
        - binary_sensor.guest_bedroom_windows
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.mode_sleep
      state: 'on'
  action:
    - service: notify.mobile_app_alexs_iphone
      data:
        title: "Condo"
        message: "The {{ trigger.to_state.attributes.friendly_name }} was opened."
        data:
          push:
            thread-id: "ha-condo-group"
            sound:
              name: "siren.wav"
              critical: 1
              volume: 1.0
