##############################################################
# Send Tasks to Things
##############################################################
# Add task to empty dust bin
- alias: Things Add Task to Empty Dust Bin - Amelia
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('vacuum.amelia', 'status', 'Dust bin full') }}"
  action:
    - service_template: rest_command.things_add_task
      data_template:
        title: "Empty Amelia's Dust Bin"
        when: "Today"
        list: "Maintenance"
- alias: Things Add Task to Empty Dust Bin - Rory
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('vacuum.rory', 'status', 'Dust bin full') }}"
  action:
    - service_template: rest_command.things_add_task
      data_template:
        title: "Empty Rory's Dust Bin"
        when: "Today"
        list: "Maintenance"
