sonos_group_morning_settings:
  alias: Sonos Group Settings - Morning
  sequence:
    - service: sonos.join
      data_template:
        master: media_player.sonos_kitchen
      entity_id:
        - media_player.sonos_rec_room
        - media_player.sonos_bedroom
        - media_player.sonos_bathroom
        - media_player.sonos_den
    - service: sonos.unjoin
      entity_id:
        - media_player.sonos_living_room
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_rec_room
      data:
        volume_level: 0.35
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_living_room
      data:
        volume_level: 0.25
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_kitchen
        - media_player.sonos_bedroom
        - media_player.sonos_bathroom
        - media_player.sonos_den
      data:
        volume_level: 0.20
