sonos_group_default_settings:
  alias: Sonos Group Settings - Default
  sequence:
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_rec_room
      data:
        volume_level: 0.32
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_kitchen
        - media_player.sonos_bedroom
        - media_player.sonos_bathroom
      data:
        volume_level: 0.28
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_living_room
      data:
        volume_level: 0.23
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_den
      data:
        volume_level: 0.20
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_move
      data:
        volume_level: 0.12
    - service: sonos.join
      data_template:
        master: media_player.sonos_kitchen
      entity_id:
        - media_player.sonos_bedroom
        - media_player.sonos_bathroom
        - media_player.sonos_den
        - media_player.sonos_living_room
        - media_player.sonos_rec_room
        - media_player.sonos_move
