##############################################################
# Home Theater On
##############################################################
- alias: Enable Home Theater On Lighting
  trigger:
    - platform: event
      event_type: mode_home_theater_on
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights: 'living_room,living_room_tv,rec_room_tiles'
- alias: Restore Home Theater Off Lighting
  trigger:
    - platform: event
      event_type: mode_home_theater_off
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights: 'living_room,living_room_tv,rec_room_tiles'


##############################################################
# Home Theater Playing
##############################################################
# Enhance with "restore" input_boolean for kitchen & living room
- alias: Enable Home Theater Playing Lighting
  trigger:
    - platform: state
      entity_id: media_player.living_room_apple_tv
      from: 'idle'
      to: 'playing'
    - platform: state
      entity_id: media_player.living_room_apple_tv
      from: 'paused'
      to: 'playing'
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights: 'kitchen,rec_room_tiles,living_room,living_room_tv'
# Enhance with "restore" input_boolean for kitchen & living room
- alias: Restore Home Theater On Lighting
  trigger:
    - platform: state
      entity_id: media_player.living_room_apple_tv
      from: 'playing'
      to: 'paused'
      for:
        seconds: 10
    - platform: state
      entity_id: media_player.living_room_apple_tv
      from: 'playing'
      to: 'idle'
    - platform: state
      entity_id: media_player.living_room_apple_tv
      from: 'paused'
      to: 'idle'
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights: 'living_room,living_room_tv,rec_room_tiles,kitchen'
