##############################################################
# Morning
##############################################################
# Triggers downstairs lights when waking up before sunrise
- alias: Downstairs Lights Before Sunrise on Motion
  trigger:
    - platform: state
      entity_id: input_boolean.motion_living_room
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      - condition: time
        after: '05:00:00'
      - condition: template
        value_template: '{{ as_timestamp(now()) | timestamp_custom("%H:%M") <= states.sensor.suncalc_goldenhourend.state | timestamp_custom("%H:%M") }}'
      - condition: state
        entity_id: input_boolean.motion_upstairs_hallway
        state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: light.kitchen
            state: 'off'
          - condition: state
            entity_id: light.rec_room_ambient
            state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.kitchen
      data:
        brightness: 3
    - service: light.turn_on
      entity_id: light.rec_room_ambient
- alias: Downstairs Lights at Sunrise
  trigger:
    - platform: template
      value_template: '{{ is_state("sensor.suncalc_sunriseend", as_timestamp(states.sensor.date.state + " " + states.sensor.time.state) | timestamp_custom("%H:%M")) }}'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
  action:
    - service: light.turn_off
      entity_id:
        - light.kitchen
        - light.living_room
