##############################################################
# Residents & Guests
##############################################################
# Welcome Lighting ###########################################
- alias: Start Welcome Lighting
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'home'
    - platform: state
      entity_id: input_boolean.mode_guest
      to: 'on'
  action:
    - choose:
        # Day Mode
        - conditions:
            - condition: state
              entity_id: input_boolean.mode_day
              state: 'on'
          sequence:
            - service: script.turn_on
              entity_id: script.update_scene
              data_template:
                variables:
                  lights: 'bedroom_tiles,den,rec_room_tiles'
      default:
        - service: script.turn_on
          entity_id: script.update_scene
          data_template:
            variables:
              lights: 'kitchen,living_room,rec_room_tiles,bedroom,bedroom_tiles,den,den_cabinets'

# Empty Home Lighting ########################################
# All residents have left the premises, but are there guests?
- alias: Start Away Lighting
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'not_home'
      # Motion Sensor Timeout
      for:
        minutes: 4
    - platform: state
      entity_id: input_boolean.mode_guest
      to: 'off'
  condition:
    - condition: state
      entity_id: group.residents
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.mode_guest
      state: 'off'
  action:
    - choose:
        # Guests Present
        - conditions:
            condition: or
            conditions:
              - condition: state
                entity_id: group.motion_guest_areas
                state: 'on'
              - condition: state
                entity_id: input_boolean.mode_home_theater
                state: 'on'
          sequence:
            - event: mode_guest_turn_on
      default:
        - service: light.turn_off
          entity_id: group.all_lights


##############################################################
# Simulate Presence Mode
##############################################################
# Used for triggering scenes when no one is home, to simulate presence
# Mode turns on a random time after no one is home
# Mode stays on for a random length of time
# Mode will turn on again after a random delay
- alias: Simulate Presence Mode - Update Lights
  trigger:
    - platform: event
      event_type: mode_simulate_presence_on
  action:
    - service: script.turn_on
      entity_id: script.simulate_presence

- alias: Simulate Presence Mode - Off
  trigger:
    - platform: event
      event_type: mode_simulate_presence_off
  action:
    - service: script.turn_off
      entity_id: script.simulate_presence
    - choose:
        # Guests Present
        - conditions:
            - condition: time
              before: '03:00:00'
          sequence:
            - service: light.turn_off
              entity_id: group.all_lights
