##############################################################
# Sleep Mode
##############################################################

- alias: Sleep Mode Started Turn Off Den Cabinet Lights
  trigger:
    - platform: event
      event_type: mode_sleep_on_delay_short
  action:
    - service: light.turn_off
      entity_id:
        - light.den_lights
        - light.den_cabinets

- alias: Sleep Mode Ended Update Lights
  trigger:
    - platform: event
      event_type: mode_sleep_off
  condition:
    - condition: state
      entity_id: group.residents
      state: 'home'
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights: 'rec_room_tiles,bedroom_tiles,bedroom,den,den_cabinets'

- alias: Sleep Mode Wake Up Time Ended Update Lights
  trigger:
    - platform: event
      event_type: mode_sleep_off_wakeup_long
  condition:
    - condition: state
      entity_id: light.bedroom_lights
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights: 'bedroom'

- alias: Sleep Mode Lights On When Patio Door Opens
  trigger:
    - platform: state
      entity_id: binary_sensor.patio_door
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.mode_sleep
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights: 'kitchen,living_room'
