##############################################################
# Sleep Mode
##############################################################

- alias: Sleep Mode Started Turn Off Den Cabinet Lights
  trigger:
    - platform: event
      event_type: mode_sleep_on_delay_short
  action:
    - service: light.turn_off
      entity_id:
        - light.den
        - light.den_cabinets
        - light.patio
        - light.patio_string

- alias: Sleep Mode Ended Update Lights
  trigger:
    - platform: event
      event_type: mode_sleep_off
  condition:
    - condition: state
      entity_id: group.residents
      state: 'home'
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights:
            - kitchen
            - rec_room_canvas
            - bedroom_tiles
            - bedroom
            - den
            - den_cabinets
    - service: number.set_value
      target:
        entity_id: number.bedroom_dimmer_default_all_led_strip_brightness_when_off
      data:
        value: 1

- alias: Sleep Mode Wake Up Time Ended Update Lights
  trigger:
    - platform: event
      event_type: mode_sleep_off_wakeup_long
  condition:
    - condition: state
      entity_id: light.bedroom
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights:
            - bedroom

- alias: Sleep Mode Lights On When Patio Door Opens
  trigger:
    - platform: state
      entity_id: binary_sensor.patio_door
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.mode_sleep
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights:
            - kitchen
            - living_room

- alias: Sleep Mode Dimmer LED Off When Lights Off
  trigger:
    - platform: state
      entity_id: group.bedroom_lights
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.mode_sleep
      state: 'on'
  action:
    - service: number.set_value
      target:
        entity_id: number.bedroom_dimmer_default_all_led_strip_brightness_when_off
      data:
        value: 0

- alias: Sleep Mode Dimmer LED On When Lights On
  trigger:
    - platform: state
      entity_id: group.bedroom_lights
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.mode_sleep
      state: 'on'
  action:
    - service: number.set_value
      target:
        entity_id: number.bedroom_dimmer_default_all_led_strip_brightness_when_off
      data:
        value: 1
