##############################################################
# Day
##############################################################
- alias: Update Lights After Sunrise
  trigger:
    - platform: event
      event_type: mode_morning_off_delay_short
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: group.residents
            state: 'home'
          - condition: state
            entity_id: input_boolean.mode_guest
            state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: light.kitchen
            state: 'on'
          - condition: state
            entity_id: light.living_room
            state: 'on'
          - condition: state
            entity_id: light.den_lights
            state: 'on'
          - condition: state
            entity_id: light.den_cabinets
            state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights:
            - kitchen
            - living_room
            - den
            - den_cabinets


##############################################################
# Sunset
##############################################################
- alias: Update Lights Before Sunset
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sunset
      to: 'on'
  action:
    - choose:
        # Someone's Home
        - conditions:
            - condition: or
              conditions:
                - condition: state
                  entity_id: group.residents
                  state: 'home'
                - condition: state
                  entity_id: input_boolean.mode_guest
                  state: 'on'
          sequence:
            - service: script.turn_on
              entity_id: script.update_lights
              data:
                variables:
                  lights:
                    - kitchen
                    - living_room
                    - living_room_tv
                    - bedroom
                    - bedroom_tiles
                    - den
                    - den_cabinets
                    - patio
                    - patio_string_lights
                  seconds: 10
      default:
        - service: script.turn_on
          entity_id: script.update_lights
          data:
            variables:
              lights:
                - patio
                - patio_string_lights


##############################################################
# Night
##############################################################
- alias: Update Lights at Night
  trigger:
    - platform: state
      entity_id: input_boolean.mode_night
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      - condition: state
        entity_id: input_boolean.mode_guest
        state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights:
            - kitchen
            - living_room
            - living_room_tv
            - bedroom
            - bedroom_tiles
            - den
            - den_cabinets
          seconds: 10


##############################################################
# Late Night
##############################################################
- alias: Update Lights at Late Night
  trigger:
    - platform: time
      at: '03:00:00'
  condition:
    - condition: state
      entity_id: group.residents
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.mode_guest
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.outside_lights


##############################################################
# Night Progressive Dimming
##############################################################
- alias: Update Lights at Night Progressive Dimming
  trigger:
    - platform: template
      value_template: '{{ is_state("sensor.prefer_lighting_mid", as_timestamp(states.sensor.date.state + " " + states.sensor.time.state) | timestamp_custom("%H:%M")) }}'
    - platform: template
      value_template: '{{ is_state("sensor.prefer_lighting_low", as_timestamp(states.sensor.date.state + " " + states.sensor.time.state) | timestamp_custom("%H:%M")) }}'
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: group.residents
            state: 'home'
          - condition: state
            entity_id: input_boolean.mode_guest
            state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: light.kitchen
            state: 'on'
          - condition: state
            entity_id: light.living_room
            state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights:
            - kitchen
            - living_room
          seconds: 10


##############################################################
# Sleep Mode - Reduce Blue Light
##############################################################
- alias: Bedroom Lights at Night - Sleep Mode On
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'on'
  condition:
    - condition: state
      entity_id: group.residents
      state: 'home'
    - condition: state
      entity_id:
        - light.bedroom_tiles
        - light.bedroom_lights
      state: 'on'
  action:
    - service: shell_command.lifx_bedroom_tiles_wakeup
    - service: light.turn_on
      entity_id: light.bedroom_tiles
      data:
        transition: 4
        brightness: 45
    - service: script.turn_on
      entity_id: script.scene_bedroom_sleep_mode_on

- alias: Bedroom Lights at Night - Sleep Mode off
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'off'
  condition:
    - condition: state
      entity_id: group.residents
      state: 'home'
    - condition: state
      entity_id:
        - light.bedroom_tiles
        - light.bedroom_lights
      state: 'on'
    - condition: state
      entity_id: input_boolean.mode_morning
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.update_lights
      data:
        variables:
          lights:
            - bedroom_tiles
            - bedroom


##############################################################
# Alexa Alarm Wakeup Light
##############################################################
# - alias: Bedroom Wakeup Light
#   trigger:
#     - platform: state
#       entity_id: sensor.alexa_wakeup_light
#       to: 'on'
#   condition:
#     - condition: state
#       entity_id: group.residents
#       state: 'home'
#     - condition: state
#       entity_id:
#         - light.bedroom_tiles
#         - light.bedroom_lights
#       state: 'off'
#   action:
#     - service: script.turn_on
#       entity_id: script.scene_bedroom_wakeup
