##############################################################
# Sunset
##############################################################
- alias: Update Lights Before Sunset
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sunset
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
  action:
    - service: script.turn_on
      entity_id: script.update_scene
      data:
        variables:
          lights: 'kitchen,living_room,living_room_tv,den,den_cabinets'


##############################################################
# Night
##############################################################
- alias: Update Lights at Night
  trigger:
    - platform: state
      entity_id: input_boolean.mode_night
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
  action:
    - service: script.turn_on
      entity_id: script.update_scene
      data:
        variables:
          lights: 'kitchen,living_room,living_room_tv,bedroom,bedroom_tiles,den,den_cabinets'


##############################################################
# Night Progressive Dimming
##############################################################
- alias: Update Lights at Night Progressive Dimming
  trigger:
    - platform: template
      value_template: '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == states("sensor.prefer_weekday_lighting_mid") }}'
    - platform: template
      value_template: '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == states("sensor.prefer_weekday_lighting_low") }}'
    - platform: template
      value_template: '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == states("sensor.prefer_weekend_lighting_mid") }}'
    - platform: template
      value_template: '{{ as_timestamp(now()) | timestamp_custom("%H:%M") == states("sensor.prefer_weekend_lighting_low") }}'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      - condition: or
        conditions:
          - condition: state
            entity_id: light.kitchen
            state: 'on'
          - condition: state
            entity_id: light.living_room
            state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.update_scene
      data_template:
        variables:
          lights: >
            {% set lights = ["kitchen","living_room"] %}

            {% for light in lights if is_state('light.'~light, 'on') -%}
                {{ light }}
              {%- if not loop.last -%}
                ,
              {%- endif %}
            {%- endfor %}


##############################################################
# Sleep Mode - Reduce Blue Light
##############################################################
- alias: Bedroom Lights at Night - Sleep Mode On
  trigger:
    platform: state
    entity_id: input_boolean.mode_sleep
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      - condition: state
        entity_id: light.bedroom_tiles
        state: 'on'
      - condition: state
        entity_id: light.bedroom_lights
        state: 'on'
  action:
    - service: shell_command.lifx_bedroom_tiles_wakeup
    - service: light.turn_on
      entity_id: light.bedroom_tiles
      data:
        transition: 4
        brightness: 45
    - service: script.turn_on
      entity_id: script.scene_bedroom_sleep_mode_on

- alias: Bedroom Lights at Night - Sleep Mode off
  trigger:
    platform: state
    entity_id: input_boolean.mode_sleep
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      - condition: state
        entity_id: light.bedroom_tiles
        state: 'on'
      - condition: state
        entity_id: light.bedroom_lights
        state: 'on'
      - condition: state
        entity_id: input_boolean.mode_morning
        state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.update_scene
      data:
        variables:
          lights: 'bedroom_tiles,bedroom'


##############################################################
# Alexa Alarm Wakeup Light
##############################################################
- alias: Bedroom Wakeup Light
  trigger:
    platform: state
    entity_id: sensor.alexa_wakeup_light
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      - condition: state
        entity_id: light.bedroom_tiles
        state: 'off'
      - condition: state
        entity_id: light.bedroom_lights
        state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.scene_bedroom_wakeup


##############################################################
# Timed Turn Off
##############################################################
# Bedroom Closet Lights Timed Out ############################
- alias: Bedroom Closet Lights Timed Out
  trigger:
    platform: state
    entity_id: light.bedroom_closet_lights
    to: 'on'
    for:
      minutes: 30
  action:
    - service: light.turn_off
      entity_id: light.bedroom_closet_lights

# Guest Bedroom Closet Lights Timed Out ######################
- alias: Guest Bedroom Closet Lights Timed Out
  trigger:
    platform: state
    entity_id: light.guest_bedroom_closet_lights
    to: 'on'
    for:
      minutes: 30
  action:
    - service: light.turn_off
      entity_id: light.guest_bedroom_closet_lights
