sonos_group_peloton_settings:
  alias: Sonos Group Settings - Peloton
  sequence:
    - service: media_player.media_pause
      data:
        entity_id: '{{ states.sensor.sonos_group_master.state }}'
    - service: sonos.unjoin
      entity_id: media_player.sonos_rec_room
    - service: media_player.volume_set
      entity_id: media_player.sonos_rec_room
      data:
        volume_level: 0.65
    - delay: '00:00:02'
    - service: media_player.select_source
      entity_id: media_player.sonos_rec_room
      data:
        source: 'Peloton: Rec Room Sonos Amp'
    - delay: '00:00:02'
    - service: media_player.media_play
      entity_id: media_player.sonos_rec_room
