sonos_group_update_settings:
  alias: Sonos Group Update Settings
  sequence:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if as_timestamp(now()) | timestamp_custom("%H:%M") >= "03:00" and as_timestamp(now()) | timestamp_custom("%H:%M") < "11:00" %}
            script.sonos_group_morning_settings
          {% elif as_timestamp(now()) | timestamp_custom("%H:%M") >= "11:00" and as_timestamp(now()) | timestamp_custom("%H:%M") < "21:00" %}
            script.sonos_group_default_settings
          {% else %}
            script.sonos_group_night_settings
          {% endif %}
