##############################################################
# Octavia
##############################################################

- alias: Octavia Event Ignition On
  trigger:
    platform: event
    event_type: automatic_update
    event_data:
      type: "ignition:on"
      vehicle:
        id: !secret automatic_vehicle_id
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.octavia_driver
        option: !secret automatic_user_id_conditional
    - service: input_select.select_option
      data_template:
        entity_id: input_select.octavia_state
        option: 'Driving'
- alias: Octavia Event Ignition Off
  trigger:
    platform: event
    event_type: automatic_update
    event_data:
      type: "ignition:off"
      vehicle:
        id: !secret automatic_vehicle_id
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.octavia_driver
        option: 'Unoccupied'
    - service: input_select.select_option
      data_template:
        entity_id: input_select.octavia_state
        option: 'Parked'
