##############################################################
# Octavia
##############################################################

# Automatic Events ###########################################
- alias: Automatic Event - Octavia Ignition On
  trigger:
    platform: event
    event_type: automatic_update
    event_data:
      type: "ignition:on"
      vehicle:
        id: !secret automatic_vehicle_id
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.octavia_driver
        option: !secret automatic_user_id_conditional
    - service: input_select.select_option
      data_template:
        entity_id: input_select.octavia_state
        option: 'Driving'
- alias: Automatic Event - Octavia Ignition Off
  trigger:
    platform: event
    event_type: automatic_update
    event_data:
      type: "ignition:off"
      vehicle:
        id: !secret automatic_vehicle_id
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.octavia_driver
        option: 'Unoccupied'
    - service: input_select.select_option
      data_template:
        entity_id: input_select.octavia_state
        option: 'Parked'

# Lack of Reliability Fix ####################################
- alias: Automatic Fix - Octavia Parked In Zone
  trigger:
    - platform: state
      entity_id: device_tracker.alexs_iphone_geofency
      to: 'home'
      for:
        minutes: 5
    - platform: state
      entity_id: device_tracker.alexs_iphone_geofency
      to: 'integrate'
      for:
        minutes: 5
    - platform: state
      entity_id: device_tracker.alexs_iphone_geofency
      to: 'dance_fx'
      for:
        minutes: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.octavia_driver
        state: 'Alex'
      - condition: state
        entity_id: input_select.octavia_state
        state: 'Driving'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.octavia_driver
        option: 'Unoccupied'
    - service: input_select.select_option
      data_template:
        entity_id: input_select.octavia_state
        option: 'Parked'
