##############################################################
# Energy Usage & Metering
##############################################################
# Select Current Energy Tariff
- alias: Energy Tariff - Select On-Peak
  trigger:
    - platform: time
      at: "16:00:00"
      variables:
        tariff: "peak"
    - platform: time
      at: "19:00:00"
      variables:
        tariff: "offpeak"
  condition:
    - condition: state
      entity_id: binary_sensor.srp_on_peak_day
      state: 'on'
  action:
    - service: select.select_option
      target:
        entity_id:
         - select.grid_consumption_daily
         - select.grid_consumption_hourly
         - select.grid_consumption_monthly
      data:
        option: "{{ tariff }}"
