##############################################################
# Bedroom
##############################################################

- alias: Fan - Bedroom - Purify Before Bed
  trigger:
    - platform: time
      at: '20:00:00'
  action:
    - service: fan.turn_on
      entity_id: fan.bedroom
    - service: dyson.set_speed
      data:
        entity_id: fan.bedroom
        dyson_speed: 8

- alias: Fan - Bedroom - Sleep Mode On
  trigger:
    - platform: event
      event_type: mode_sleep_on
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'on'
  action:
    - service: dyson.set_night_mode
      data:
        entity_id: fan.bedroom
        night_mode: true
    - service: dyson.set_speed
      data:
        entity_id: fan.bedroom
        dyson_speed: 4

- alias: Fan - Bedroom - Sleep Mode Off - Wakeup Short
  trigger:
    - platform: event
      event_type: mode_sleep_off_wakeup_short
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'on'
  action:
    - service: dyson.set_night_mode
      data:
        entity_id: fan.bedroom
        night_mode: false
    - service: dyson.set_speed
      data:
        entity_id: fan.bedroom
        dyson_speed: 8

- alias: Fan - Bedroom - Sleep Mode Off - Wakeup Long
  trigger:
    - platform: event
      event_type: mode_sleep_off_wakeup_long
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'on'
  action:
    - service: dyson.set_speed
      data:
        entity_id: fan.bedroom
        dyson_speed: 4

- alias: Fan - Bedroom - Bedroom Window Open
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_windows
      to: 'on'
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'on'
  action:
    - service: fan.turn_off
      entity_id: fan.bedroom

- alias: Fan - Bedroom - Bedroom Window Closed
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_windows
      to: 'off'
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'off'
  action:
    - service: fan.turn_on
      entity_id: fan.bedroom
    - choose:
        # After 7:00pm
        - conditions:
            - condition: time
              after: '20:00:00'
          sequence:
            - service: dyson.set_speed
              data:
                entity_id: fan.bedroom
                dyson_speed: 8
      default:
        - service: dyson.set_speed
          data:
            entity_id: fan.bedroom
            dyson_speed: 4


##############################################################
# Kitchen
##############################################################

- alias: Fan - Kitchen - Sleep Mode On
  trigger:
    - platform: event
      event_type: mode_sleep_on
  condition:
    - condition: state
      entity_id: fan.kitchen
      state: 'on'
  action:
    - service: dyson.set_night_mode
      data:
        entity_id: fan.kitchen
        night_mode: true

- alias: Fan - Kitchen - Sleep Mode Off
  trigger:
    - platform: event
      event_type: mode_sleep_off
  condition:
    - condition: state
      entity_id: fan.kitchen
      state: 'on'
    - condition: time
      after: '05:00:00'
  action:
    - service: dyson.set_night_mode
      data:
        entity_id: fan.kitchen
        night_mode: false
