##############################################################
# Bedroom
##############################################################
- alias: Bedroom Fan Speed - Sleep Mode Wake Up Time Ended
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'off'
      for:
        hours: 3
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'on'
  action:
    - service: dyson.set_speed
      data:
        entity_id: fan.bedroom
        dyson_speed: 5

- alias: Bedroom Fan Speed - Before Bed
  trigger:
    - platform: time
      at: '19:00:00'
  action:
    - service: fan.turn_on
      entity_id: fan.bedroom
    - service: dyson.set_speed
      data:
        entity_id: fan.bedroom
        dyson_speed: 8

- alias: Bedroom Fan Speed - Sleep Mode Started
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'on'
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'on'
  action:
    - service: dyson.set_night_mode
      data:
        entity_id: fan.bedroom
        night_mode: true
    - service: dyson.set_speed
      data:
        entity_id: fan.bedroom
        dyson_speed: 5

- alias: Bedroom Fan Speed - Sleep Mode Ended
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'off'
      for:
        minutes: 20
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'on'
    - condition: time
      after: '05:00:00'
  action:
    - service: dyson.set_night_mode
      data:
        entity_id: fan.bedroom
        night_mode: false
    - service: dyson.set_speed
      data:
        entity_id: fan.bedroom
        dyson_speed: 8

- alias: Bedroom Fan Speed - Bedroom Window Open
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_windows
      to: 'on'
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'on'
  action:
    - service: fan.turn_off
      entity_id: fan.bedroom

- alias: Bedroom Fan Speed - Bedroom Window Closed
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_windows
      to: 'off'
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'off'
    - condition: time
      after: '19:00:00'
  action:
    - service: fan.turn_on
      entity_id: fan.bedroom
    - service: dyson.set_speed
      data:
        entity_id: fan.bedroom
        dyson_speed: 8
