##############################################################
# Bedroom
##############################################################
- alias: Bedroom Fan Speed Away on Weekday Morning
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: fan.bedroom
        state: 'on'
      - condition: template
        value_template: '{{ now().strftime("%A") | lower in ["monday", "tuesday", "wednesday", "thursday", "friday"] }}'
      - condition: time
        before: '10:00:00'
  action:
    - service: fan.turn_off
      entity_id: fan.bedroom

- alias: Bedroom Fan Speed on Weekday Morning
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'off'
      for:
        hours: 3
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      - condition: state
        entity_id: fan.bedroom
        state: 'on'
      - condition: template
        value_template: '{{ now().strftime("%A") | lower in ["monday", "tuesday", "wednesday", "thursday", "friday"] }}'
  action:
    - service: dyson.set_speed
      data:
        entity_id: fan.bedroom
        dyson_speed: 4


- alias: Bedroom Fan Speed on Weekend Morning
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'off'
      for:
        hours: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: fan.bedroom
        state: 'on'
      - condition: template
        value_template: '{{ now().strftime("%A") | lower in ["saturday", "sunday"] }}'
  action:
    - service: dyson.set_speed
      data:
        entity_id: fan.bedroom
        dyson_speed: 4

- alias: Bedroom Fan Speed Before Bed
  trigger:
    - platform: time
      at: '19:00:00'
  action:
    - service: fan.turn_on
      entity_id: fan.bedroom
    - service: dyson.set_speed
      data:
        entity_id: fan.bedroom
        dyson_speed: 8

- alias: Bedroom Fan Speed Sleep Mode Started
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'on'
      for:
        minutes: 2
  action:
    - service: fan.turn_on
      entity_id: fan.bedroom
    - service: dyson.set_night_mode
      data:
        entity_id: fan.bedroom
        night_mode: true

- alias: Bedroom Fan Speed Sleep Mode Ended
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'off'
      for:
        minutes: 10
  action:
    - service: fan.turn_on
      entity_id: fan.bedroom
    - service: dyson.set_night_mode
      data:
        entity_id: fan.bedroom
        night_mode: false
