##############################################################
# Bedroom
##############################################################

- alias: Fan - Bedroom - Sleep Mode On
  trigger:
    - platform: event
      event_type: mode_sleep_on
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.bedroom_night_mode
    - service: fan.set_percentage
      data:
        entity_id: fan.bedroom
        percentage: 40

- alias: Fan - Bedroom - Sleep Mode Off
  trigger:
    - platform: event
      event_type: mode_sleep_off
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.bedroom_night_mode
    - service: fan.set_percentage
      data:
        entity_id: fan.bedroom
        percentage: 40

- alias: Fan - Bedroom - Bedroom Window Open
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_windows
      to: 'on'
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'on'
  action:
    - service: fan.turn_off
      entity_id: fan.bedroom

- alias: Fan - Bedroom - Bedroom Window Closed
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_windows
      to: 'off'
  condition:
    - condition: state
      entity_id: fan.bedroom
      state: 'off'
  action:
    - service: fan.turn_on
      entity_id: fan.bedroom


##############################################################
# Kitchen
##############################################################

- alias: Fan - Kitchen - Sleep Mode On
  trigger:
    - platform: event
      event_type: mode_sleep_on
  condition:
    - condition: state
      entity_id: fan.kitchen
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_night_mode

- alias: Fan - Kitchen - Sleep Mode Off
  trigger:
    - platform: event
      event_type: mode_sleep_off
  condition:
    - condition: state
      entity_id: fan.kitchen
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_night_mode
    - service: fan.set_percentage
      data:
        entity_id: fan.kitchen
        percentage: 50
