##############################################################
# Motion Events - Anytime
##############################################################

# Garage Lighting on Motion ##################################
- alias: Garage Lighting on Motion
  trigger:
    - platform: state
      entity_id: input_boolean.motion_garage
      to: 'on'
  condition:
    - condition: state
      entity_id: light.garage
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.garage
    - service: input_boolean.turn_on
      entity_id: input_boolean.motion_trigger_garage_lights

# Garage Lighting on Door Open ###############################
- alias: Garage Lighting on Garage Actual Open
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_actual
      to: 'on'
  condition:
    - condition: state
      entity_id: light.garage
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.garage
    - service: input_boolean.turn_on
      entity_id: input_boolean.door_trigger_garage_lights
# Separated to add delay on the Garage Door so they do not
# immmediately turn back on if turned off before entering
- alias: Garage Lighting on Garage Door Open
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door
      to: 'on'
  condition:
    - condition: state
      entity_id: light.garage
      state: 'off'
      for:
        minutes: 1
  action:
    - service: light.turn_on
      entity_id: light.garage
    - service: input_boolean.turn_on
      entity_id: input_boolean.door_trigger_garage_lights

# Garage Lighting Timed Out ##################################
# Transitions from a door to a motion trigger, so lights
# do not turn out if someone stays in the motion zone.
- alias: Garage Lighting Door to Motion Transition
  trigger:
    - platform: state
      entity_id: input_boolean.motion_garage
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.door_trigger_garage_lights
      state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.motion_trigger_garage_lights
    - service: input_boolean.turn_off
      entity_id: input_boolean.door_trigger_garage_lights
- alias: Garage Lighting on Gragage Actual Timed Out
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.garage_actual
        - input_boolean.motion_garage
      to: 'off'
  condition:
    - condition: state
      entity_id:
        - input_boolean.motion_garage
        - binary_sensor.garage_actual
      state: 'off'
    - condition: state
      entity_id:
        - input_boolean.motion_trigger_garage_lights
        - light.garage
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.garage
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.door_trigger_garage_lights
        - input_boolean.motion_trigger_garage_lights

##############################################################
# NFC Events
##############################################################
- alias: Garage Actual Trigger from NFC Tag
  trigger:
    - platform: event
      event_type: nfc_garage_actual_toggle
  action:
    - service: cover.toggle
      entity_id: cover.garage_actual
