##############################################################
# Presence Events - Home
##############################################################

# Welcome Lighting at Night ##################################
- alias: Welcome Lighting at Night
  trigger:
    platform: state
    entity_id: device_tracker.alex_alexs_iphone
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.kitchen_lights
        state: 'off'
      - condition: state
        entity_id: input_boolean.trigger_night_mode
        state: 'on'
  action:
    - service: shell_command.hyperion_mood_blobs_blue
    - service: script.turn_on
      entity_id: script.scene_select_by_time
      data:
        variables:
          room: living_room
    - delay: '00:00:01'
    - service: script.turn_on
      entity_id: script.scene_select_by_time
      data:
        variables:
          room: kitchen
    - delay: '00:03:00'
    - service: script.turn_on
      entity_id: script.scene_select_living_room_ambient

##############################################################
# Presence Events - Away
##############################################################

# Empty Home Lighting ########################################
# All residents and guests have left the premises.
- alias: Start Away Lighting
  trigger:
    - platform: state
      entity_id: device_tracker.alex_alexs_iphone
      to: 'not_home'
    - platform: state
      entity_id: input_boolean.trigger_guest_mode
      to: 'off'
    - platform: state
      entity_id: input_boolean.trigger_night_mode
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.alex_alexs_iphone
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.trigger_guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.trigger_night_mode
        state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.scene_select_away_lighting



# Furry Overlord Lighting ####################################
# Turn on Living Room light at night, when no one is home, if it's before 11:00pm
- alias: Start Furry Overlord Lighting
  trigger:
    - platform: event
      event_type: event_start_furry_overlord_lighting
  condition:
    condition: and
    conditions:
      - condition: time
        before: '23:00:00'
  action:
    service: script.turn_on
    entity_id: script.scene_select_living_room_dim
# Turn off Living Room light between 2:02am and 2:55am
- alias: End Furry Overlord Lighting
  trigger:
    - platform: time
      at: '02:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.alex_alexs_iphone
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.trigger_guest_mode
        state: 'off'
      - condition: state
        entity_id: group.living_room_lights
        state: 'on'
  action:
    - delay: '00:{{ (range(2, 55) | random) }}:00'
    - service: switch.turn_off
      entity_id: switch.living_room_lights

# Simulate Presence ##########################################
# Simulate presence between 5:00pm and 3:00am, Night Mode determines actual start time
# Turn on the kitchen lights when no one is home
# Lights turn on a random time after one one is home
# Lights stay on for a random length of time
# Lights will turn on again after a random delay
- alias: Simulate Presence at Night
  trigger:
    - platform: state
      entity_id: device_tracker.alex_alexs_iphone
      to: 'not_home'
      for:
        minutes: 20
    - platform: state
      entity_id: input_boolean.trigger_guest_mode
      to: 'off'
      for:
        minutes: 20
    - platform: state
      entity_id: input_boolean.trigger_night_mode
      to: 'on'
    - platform: event
      event_type: event_simulate_presence
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trigger_night_mode
        state: 'on'
      - condition: state
        entity_id: device_tracker.alex_alexs_iphone
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.trigger_guest_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: time
            after: '17:00:00'
          - condition: time
            before: '03:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_dim_at_night
    - delay: '00:{{ (range(2, 10) | random) }}:00'
    - service: light.turn_off
      entity_id: group.kitchen_lights
    - delay: '00:{{ (range(35, 55) | random) }}:00'
    - event: event_simulate_presence

##############################################################
# Timed Events - Home
##############################################################

# Lights at Sunset ###########################################
- alias: Sunset Lighting Slow
  trigger:
    platform: state
    entity_id: input_boolean.trigger_sunset_mode
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.kitchen_overhead_lights
        state: 'off'
      - condition: state
        entity_id: group.kitchen_island_lights
        state: 'off'
      - condition: state
        entity_id: device_tracker.alex_alexs_iphone
        state: 'home'
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state('input_boolean.trigger_home_theater_mode', 'on') %}
            script.scene_select_sunset_home_theater_mode_on
          {% else %}
            script.scene_select_sunset_home_theater_mode_off
          {% endif %}

# Kitchen Lights After Sunset ################################
- alias: Night Lighting Default Slow
  trigger:
    platform: state
    entity_id: input_boolean.trigger_sunset_mode
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.kitchen_overhead_lights
        state: 'on'
      - condition: state
        entity_id: group.kitchen_island_lights
        state: 'on'
      - condition: state
        entity_id: device_tracker.alex_alexs_iphone
        state: 'home'
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state('input_boolean.trigger_home_theater_mode', 'on') %}
            script.scene_select_night_home_theater_mode_on
          {% else %}
            script.scene_select_night_home_theater_mode_off
          {% endif %}

##############################################################
# Timed Events - Away
##############################################################

# Guest Lighting at Night ####################################
# This is the trigger inverse of "Guest Lighting on Motion"
- alias: Guest Lighting at Night
  trigger:
    platform: state
    entity_id: input_boolean.trigger_night_mode
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.alex_alexs_iphone
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.trigger_guest_mode
        state: 'on'
      - condition: state
        entity_id: group.kitchen_overhead_lights
        state: 'off'
      - condition: state
        entity_id: group.kitchen_island_lights
        state: 'off'
  action:
    service: scene.turn_on
    entity_id:
      - scene.kitchen_bright_at_night
      - scene.living_room_bright_at_night


##############################################################
# Motion Events - Anytime
##############################################################

# Bathroom Lighting on Motion ################################
# Triggers when LUX is below X, or when Night Mode is on
- alias: Bathroom Lighting on Motion
  trigger:
    platform: state
    entity_id: input_boolean.motion_bathroom
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.bathroom_lights
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.trigger_night_mode
            state: 'on'
          - condition: numeric_state
            entity_id: sensor.bathroom_multisensor_luminance
            below: 5.0
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state('input_boolean.trigger_sleep_mode', 'off') %}
            script.scene_select_bathroom_dim
          {% else %}
            script.scene_select_bathroom_nightlight
          {% endif %}
      data:
        variables:
          motion_trigger: true
- alias: Bathroom Lighting Timed Out
  trigger:
    platform: state
    entity_id: input_boolean.motion_bathroom
    to: 'off'
#   for:
#     minutes: 1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.motion_trigger_bathroom_lights
        state: 'on'
  action:
    - service: light.turn_off
      entity_id: group.bathroom_lights
    - service: homeassistant.turn_off
      entity_id: input_boolean.motion_trigger_bathroom_lights

# Bedroom Lighting on Motion #################################
# Triggers only while while Sleep Mode is off
# Triggers when LUX is below X, or when Night Mode is on
- alias: Bedroom Lighting on Motion
  trigger:
    platform: state
    entity_id: input_boolean.motion_bedroom
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trigger_sleep_mode
        state: 'off'
      - condition: state
        entity_id: group.bedroom_lights
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.trigger_night_mode
            state: 'on'
          - condition: numeric_state
            entity_id: sensor.bedroom_multisensor_luminance
            below: 5.0
  action:
    - service: script.turn_on
      entity_id: script.scene_select_bedroom_dim
      data:
        variables:
          motion_trigger: true
- alias: Bedroom Lighting Timed Out
  trigger:
    platform: state
    entity_id: input_boolean.motion_bedroom
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trigger_sleep_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.motion_trigger_bedroom_lights
        state: 'on'
      - condition: time
        after: '06:00:00'
        before: '21:00:00'
  action:
    - service: light.turn_off
      entity_id: group.bedroom_lights
    - service: homeassistant.turn_off
      entity_id: input_boolean.motion_trigger_bedroom_lights
- alias: Bedroom Lighting Timed Out during Bedtime
  trigger:
    platform: state
    entity_id: input_boolean.motion_bedroom
    to: 'off'
    # Extend the timeout during bedtime to allow for beacon delay
    for:
      minutes: 3
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trigger_sleep_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.motion_trigger_bedroom_lights
        state: 'on'
      - condition: or
        conditions:
          - condition: time
            after: '21:00:00'
          - condition: time
            before: '06:00:00'
  action:
    - service: light.turn_off
      entity_id: group.bedroom_lights
    - service: homeassistant.turn_off
      entity_id: input_boolean.motion_trigger_bedroom_lights

##############################################################
# Motion Events - Home
##############################################################


##############################################################
# Motion Events - Away
##############################################################

# Guest Lighting on Motion ###################################
# This is the trigger inverse of "Guest Lighting at Night"
- alias: Guest Lighting on Motion
  trigger:
    platform: state
    entity_id: input_boolean.trigger_guest_mode
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.alex_alexs_iphone
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.trigger_night_mode
        state: 'on'
      - condition: state
        entity_id: group.kitchen_overhead_lights
        state: 'off'
      - condition: state
        entity_id: group.kitchen_island_lights
        state: 'off'
  action:
    service: scene.turn_on
    entity_id:
      - scene.kitchen_bright_at_night
      - scene.living_room_bright_at_night
- alias: Guest Lighting Timed Out
  trigger:
    platform: state
    entity_id: input_boolean.trigger_guest_mode
    to: 'off'
  condition:
    condition: state
    entity_id: device_tracker.alex_alexs_iphone
    state: 'not_home'
  action:
    service: light.turn_off
    entity_id: 
      - group.all_lights

##############################################################
# Events - Home
##############################################################

# Dim Lights While Watching Plex on Apple TV #################
- alias: Enable Home Theater Scene Durring Night
  trigger:
    platform: state
    entity_id: input_boolean.trigger_home_theater_mode
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trigger_night_mode
        state: 'on'
  action:
    service: script.turn_on
    entity_id: script.scene_select_home_theater_mode_on
- alias: Restore Post Home Theater Scene Durring Night
  trigger:
    platform: state
    entity_id: input_boolean.trigger_home_theater_mode
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trigger_night_mode
        state: 'on'
  action:
    service: script.turn_on
    entity_id: script.scene_select_home_theater_mode_off

# Turn Off Lights While Watching Plex in Sleep Mode ##########
- alias: Sleep Mode Lights Out Plex
  trigger:
    platform: state
    entity_id: media_player.plex_alex_bussas_ipad_mini
    to: 'playing'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.alex_alexs_iphone
        state: 'home'
      - condition: state
        entity_id: input_boolean.trigger_sleep_mode
        state: 'on'
      - condition: state
        entity_id: group.bedroom_lights
        state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_bedtime_fade_out


##############################################################
# Color Loops
##############################################################

# Kitchen Overhead Lights ####################################
- alias: Continue Color Loop Kitchen Overhead Lights
  trigger:
    - platform: state
      entity_id: input_boolean.color_loop_kitchen_overhead
      to: 'on'
    - platform: event
      event_type: event_color_loop_kitchen_overhead
  condition:
    condition: state
    entity_id: input_boolean.color_loop_kitchen_overhead
    state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.scene_select_color_loop_kitchen_overhead
    - delay: '00:00:{{ (range(2, 10) | random) }}'
    - event: event_color_loop_kitchen_overhead

# Bedroom Lights #############################################
- alias: Continue Color Loop Bedroom Lights
  trigger:
    - platform: state
      entity_id: input_boolean.color_loop_bedroom
      to: 'on'
    - platform: event
      event_type: event_color_loop_bedroom
  condition:
    condition: state
    entity_id: input_boolean.color_loop_bedroom
    state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.scene_select_color_loop_bedroom
    - delay: '00:00:{{ (range(2, 10) | random) }}'
    - event: event_color_loop_bedroom

# Living Room Lights #########################################
- alias: Continue Color Loop Living Room Lights
  trigger:
    - platform: state
      entity_id: input_boolean.color_loop_living_room
      to: 'on'
    - platform: event
      event_type: event_color_loop_Living_room
  condition:
    condition: state
    entity_id: input_boolean.color_loop_living_room
    state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.color_loop_living_room_trigger
    - delay: '00:00:{{ (range(50, 120) | random) }}'
    - event: event_color_loop_Living_room
