##############################################################
# Residents & Guests
##############################################################
# Welcome Lighting ###########################################
- alias: Start Welcome Lighting
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'home'
    - platform: state
      entity_id: input_boolean.mode_guest
      to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.mode_simulate_presence
    - delay: '00:00:05'
    - service: script.turn_on
      entity_id: script.update_scene
      data_template:
        variables:
          lights: >-
            {%- if is_state('input_boolean.mode_morning', 'on') or is_state('input_boolean.mode_sunset', 'on') or is_state('input_boolean.mode_night', 'on') -%}
              kitchen,living_room,rec_room_ambient,bedroom_ambient,den_cabinets
            {%- else -%}
              bedroom_ambient,rec_room_ambient
            {%- endif %}

# Empty Home Lighting ########################################
# All residents have left the premises, but are there guests?
- alias: Start Away Lighting
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'not_home'
      for:
        minutes: 4
    - platform: state
      entity_id: input_boolean.mode_guest
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.mode_guest
        state: 'off'
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state('group.motion_guest_areas', 'on') or is_state('input_boolean.mode_home_theater', 'on') %}
            script.mode_turn_on_guest_mode
          {% else %}
            script.scene_empty_home
          {% endif %}

# Simulate Presence ##########################################
- alias: Start Simulating Presence at Night
  trigger:
    - platform: state
      entity_id: input_boolean.mode_simulate_presence
      to: 'on'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: '{{ states.group.simulate_presence_scenes.attributes.entity_id | random }}'

- alias: End Simulating Presence at Night
  trigger:
    - platform: state
      entity_id: input_boolean.mode_simulate_presence
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: all


##############################################################
# Sleep Mode
##############################################################

- alias: Sleep Mode Started Turn Off Den Cabinet Lights
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'on'
      for:
        minutes: 2
  action:
    - service: light.turn_off
      entity_id:
        - light.den_cabinets

- alias: Sleep Mode Ended Update Lights
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'off'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: group.residents
      state: 'home'
  action:
    - service: script.turn_on
      entity_id: script.update_scene
      data:
        variables:
          lights: 'rec_room_ambient,den_cabinets'

- alias: Sleep Mode Lights On When Patio Door Opens
  trigger:
    - platform: state
      entity_id: binary_sensor.patio_door
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.mode_sleep
    state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.update_scene
      data:
        variables:
          lights: 'kitchen,living_room'
