##############################################################
# Presence Events - Home
##############################################################

# Welcome Lighting at Night ##################################
- alias: Welcome Lighting at Night
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trigger_night_mode
        state: 'on'
      - condition: state
        entity_id: group.kitchen_overhead_lights
        state: 'off'
      - condition: state
        entity_id: group.kitchen_island_lights
        state: 'off'
  action:
    service: scene.turn_on
    entity_id:
      - scene.kitchen_bright_at_night
      - scene.living_room_bright_at_night

##############################################################
# Presence Events - Away
##############################################################

# Furry Overlord Lighting ####################################
# The hoomans are gone, turn off the lights, but leave one on...
# Just because I can see in the dark, doesn't mean I want to be in the dark.
# Turn on Living Room light at night, when no one is home
- alias: Away Lighting Default
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'not_home'
    - platform: state
      entity_id: input_boolean.trigger_guest_mode
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trigger_night_mode
        state: 'on'
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.trigger_guest_mode
        state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.away_lighting_at_night

# Simulate Presence ##########################################
# Turn on the kitchen lights when no one is home
# Lights turn on a random time after one one is home
# Lights stay on for a random length of time
# Lights will turn on again after a random delay
- alias: Simulate Presence at Night
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'not_home'
      for:
        minutes: 20
    - platform: state
      entity_id: input_boolean.trigger_guest_mode
      to: 'off'
      for:
        minutes: 20
    - platform: event
      event_type: event_simulate_presence
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trigger_night_mode
        state: 'on'
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.trigger_guest_mode
        state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_dim_at_night
    - delay: '00:{{ (range(2, 10) | random) }}:00'
    - service: light.turn_off
      entity_id: group.kitchen_lights
    - delay: '00:{{ (range(35, 55) | random) }}:00'
    - event: event_simulate_presence

##############################################################
# Timed Events - Home
##############################################################

# Kitchen Lights at Sunset ###################################
- alias: Sunset Lighting Slow
  trigger:
    platform: state
    entity_id: input_boolean.trigger_sunset_mode
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.kitchen_overhead_lights
        state: 'off'
      - condition: state
        entity_id: group.kitchen_island_lights
        state: 'off'
      - condition: state
        entity_id: device_tracker.alex_alexs_iphone
        state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_bright_at_sunset_slow

# Kitchen Lights After Sunset ################################
- alias: Night Lighting Default Slow
  trigger:
    platform: state
    entity_id: input_boolean.trigger_sunset_mode
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.kitchen_overhead_lights
        state: 'on'
      - condition: state
        entity_id: group.kitchen_island_lights
        state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_bright_at_night_slow


##############################################################
# Timed Events - Away
##############################################################

# Guest Lighting at Night ####################################
# This is the trigger inverse of "Guest Lighting on Motion"
- alias: Guest Lighting at Night
  trigger:
    platform: state
    entity_id: input_boolean.trigger_night_mode
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.trigger_guest_mode
        state: 'on'
      - condition: state
        entity_id: group.kitchen_overhead_lights
        state: 'off'
      - condition: state
        entity_id: group.kitchen_island_lights
        state: 'off'
  action:
    service: scene.turn_on
    entity_id:
      - scene.kitchen_bright_at_night
      - scene.living_room_bright_at_night


##############################################################
# Motion Events - Anytime
##############################################################

# Bathroom Lighting on Motion ################################
# Triggers when LUX is below X, or when Night Mode is on
- alias: Bathroom Lighting on Motion
  trigger:
    platform: state
    entity_id: input_boolean.motion_bathroom
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.bathroom_lights
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.trigger_night_mode
            state: 'on'
          - condition: numeric_state
            entity_id: sensor.bathroom_multisensor_luminance
            below: 5.0
  action:
    - service: script.turn_on
      entity_id: script.scene_select_bathroom_dim
      data:
        variables:
          motion_trigger: true
- alias: Bathroom Lighting Timed Out
  trigger:
    platform: state
    entity_id: input_boolean.motion_bathroom
    to: 'off'
#   for:
#     minutes: 1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.motion_trigger_bathroom_lights
        state: 'on'
  action:
    - service: light.turn_off
      entity_id: group.bathroom_lights
    - service: homeassistant.turn_off
      entity_id: input_boolean.motion_trigger_bathroom_lights

# Bedroom Lighting on Motion #################################
# Triggers only while while Sleep Mode is off
# Triggers when LUX is below X, or when Night Mode is on
- alias: Bedroom Lighting on Motion
  trigger:
    platform: state
    entity_id: input_boolean.motion_bedroom
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trigger_sleep_mode
        state: 'off'
      - condition: state
        entity_id: group.bedroom_lights
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.trigger_night_mode
            state: 'on'
          - condition: numeric_state
            entity_id: sensor.bedroom_multisensor_luminance
            below: 5.0
  action:
    - service: script.turn_on
      entity_id: script.scene_select_bedroom_dim
      data:
        variables:
          motion_trigger: true
- alias: Bedroom Lighting Timed Out
  trigger:
    platform: state
    entity_id: input_boolean.motion_bedroom
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trigger_sleep_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.motion_trigger_bedroom_lights
        state: 'on'
      - condition: time
        after: '06:00:00'
        before: '21:00:00'
  action:
    - service: light.turn_off
      entity_id: group.bedroom_lights
    - service: homeassistant.turn_off
      entity_id: input_boolean.motion_trigger_bedroom_lights
- alias: Bedroom Lighting Timed Out during Bedtime
  trigger:
    platform: state
    entity_id: input_boolean.motion_bedroom
    to: 'off'
    # Extend the timeout during bedtime to allow for beacon delay
    for:
      minutes: 3
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trigger_sleep_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.motion_trigger_bedroom_lights
        state: 'on'
      - condition: or
        conditions:
          - condition: time
            after: '21:00:00'
          - condition: time
            before: '06:00:00'
  action:
    - service: light.turn_off
      entity_id: group.bedroom_lights
    - service: homeassistant.turn_off
      entity_id: input_boolean.motion_trigger_bedroom_lights

##############################################################
# Motion Events - Home
##############################################################


##############################################################
# Motion Events - Away
##############################################################

# Guest Lighting on Motion ###################################
# This is the trigger inverse of "Guest Lighting at Night"
- alias: Guest Lighting on Motion
  trigger:
    platform: state
    entity_id: input_boolean.trigger_guest_mode
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.trigger_night_mode
        state: 'on'
      - condition: state
        entity_id: group.kitchen_overhead_lights
        state: 'off'
      - condition: state
        entity_id: group.kitchen_island_lights
        state: 'off'
  action:
    service: scene.turn_on
    entity_id:
      - scene.kitchen_bright_at_night
      - scene.living_room_bright_at_night
- alias: Guest Lighting Timed Out
  trigger:
    platform: state
    entity_id: input_boolean.trigger_guest_mode
    to: 'off'
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'not_home'
  action:
    service: light.turn_off
    entity_id: 
      - group.all_lights

##############################################################
# Events - Home
##############################################################

# Turn Off Lights w Plex in Sleep Mode #######################
- alias: Sleep Mode Lights Out Plex
  trigger:
    platform: state
    entity_id: media_player.plex_alex_bussas_ipad_mini
    to: 'playing'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: state
        entity_id: input_boolean.trigger_sleep_mode
        state: 'on'
      - condition: state
        entity_id: group.bedroom_lights
        state: 'on'
  action:
    service: light.turn_off
    entity_id: group.bedroom_lights
