# Lock Front Door When Away or Asleep ########################
- alias: Lock Front Door When Away or Asleep
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'on'
    - platform: state
      entity_id: group.residents
      to: 'not_home'
  condition:
    condition: state
    entity_id: lock.august_smart_lock_pro_front_door
    state: 'unlocked'
  action:
    - service: lock.lock
      entity_id: lock.august_smart_lock_pro_front_door

# Lock Garage Door When Away or Asleep #######################
- alias: Lock Garage Door When Away or Asleep
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'on'
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'on'
      for:
        minutes: 2
    - platform: state
      entity_id: group.residents
      to: 'not_home'
    - platform: state
      entity_id: group.residents
      to: 'not_home'
      for:
        minutes: 2
  condition:
    condition: state
    entity_id: lock.august_smart_lock_pro_garage_door
    state: 'unlocked'
  action:
    - service: lock.lock
      entity_id: lock.august_smart_lock_pro_garage_door

# Unlock Garage Door When Home and Awake #####################
- alias: Unlock Garage Door When Home and Awake
  trigger:
    - platform: state
      entity_id: input_boolean.mode_sleep
      to: 'off'
      for:
        minutes: 2
    - platform: state
      entity_id: group.residents
      to: 'home'
  condition:
    condition: state
    entity_id: lock.august_smart_lock_pro_garage_door
    state: 'locked'
  action:
    - service: lock.unlock
      entity_id: lock.august_smart_lock_pro_garage_door
