##############################################################
# Timed Modes
##############################################################

# Morning Mode ################################################
- alias: Mode - Morning On
  trigger:
    - platform: template
      value_template: '{{ is_state("sensor.suncalc_nightend", as_timestamp(states.sensor.date.state + " " + states.sensor.time.state) | timestamp_custom("%H:%M")) }}'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.mode_morning
- alias: Mode - Morning Off
  trigger:
    - platform: template
      value_template: '{{ is_state("sensor.suncalc_goldenhourend", as_timestamp(states.sensor.date.state + " " + states.sensor.time.state) | timestamp_custom("%H:%M")) }}'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.mode_morning

# Day Mode ################################################
- alias: Mode - Day On
  trigger:
    - platform: template
      value_template: '{{ is_state("sensor.suncalc_goldenhourend", as_timestamp(states.sensor.date.state + " " + states.sensor.time.state) | timestamp_custom("%H:%M")) }}'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.mode_day
- alias: Mode - Day Off
  trigger:
    - platform: template
      value_template: '{{ is_state("sensor.suncalc_goldenhour", as_timestamp(states.sensor.date.state + " " + states.sensor.time.state) | timestamp_custom("%H:%M")) }}'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.mode_day

# Sunset Mode ################################################
- alias: Mode - Sunset On
  trigger:
    - platform: template
      value_template: '{{ is_state("sensor.suncalc_goldenhour", as_timestamp(states.sensor.date.state + " " + states.sensor.time.state) | timestamp_custom("%H:%M")) }}'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.mode_sunset
- alias: Mode - Sunset Off
  trigger:
    - platform: template
      value_template: '{{ is_state("sensor.suncalc_sunsetstart", as_timestamp(states.sensor.date.state + " " + states.sensor.time.state) | timestamp_custom("%H:%M")) }}'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.mode_sunset

# Night Mode #################################################
- alias: Mode - Night On
  trigger:
    - platform: template
      value_template: '{{ is_state("sensor.suncalc_sunsetstart", as_timestamp(states.sensor.date.state + " " + states.sensor.time.state) | timestamp_custom("%H:%M")) }}'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.mode_night
- alias: Mode - Night Off
  trigger:
    - platform: template
      value_template: '{{ is_state("sensor.suncalc_nightend", as_timestamp(states.sensor.date.state + " " + states.sensor.time.state) | timestamp_custom("%H:%M")) }}'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.mode_night

##############################################################
# Event Modes
##############################################################

# Guest Mode #################################################
- alias: Mode - Guest On
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.garage_actual
        - binary_sensor.garage_door
        - binary_sensor.front_door
      to: 'on'
    - platform: event
      event_type: mode_guest_turn_on
  condition:
    - condition: state
      entity_id: group.residents
      state: 'not_home'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.mode_guest
- alias: Mode - Guest Off
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'home'
    - platform: state
      entity_id: group.motion_guest_areas
      to: 'off'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.mode_home_theater
      state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.mode_guest

# Simulate Presence Mode #####################################
# Turns on between 5:00pm and 3:00am, Night Mode determines actual start time
- alias: Mode - Simulate Presence On
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'not_home'
      # Motion Sensor Timeout
      for:
        minutes: 4
    - platform: state
      entity_id: input_boolean.mode_guest
      to: 'off'
    - platform: state
      entity_id: input_boolean.mode_night
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.mode_night
        state: 'on'
      - condition: state
        entity_id: group.residents
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.mode_guest
        state: 'off'
      - condition: or
        conditions:
          - condition: time
            after: '17:00:00'
          - condition: time
            before: '03:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.mode_simulate_presence
- alias: Mode - Simulate Presence Off
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'home'
    - platform: state
      entity_id: input_boolean.mode_guest
      to: 'on'
    - platform: time
      at: "03:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.mode_simulate_presence
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.mode_simulate_presence

# Sleep Mode #################################################
# Starts when bedroom beacon is detected during bedtime.
# Lognger delay before exiting mode, beacon detection is spotty.
- alias: Mode - Sleep On
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: MODE_SLEEP_ON
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.mode_sleep
- alias: Mode - Sleep Off
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: MODE_SLEEP_OFF
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.mode_sleep


# Peloton Mode #################################################
- alias: Mode - Peloton Off
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: MODE_PELOTON_OFF
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.mode_peloton


# Home Theater Mode ##########################################
- alias: Mode - Home Theater On
  trigger:
    - platform: state
      entity_id: media_player.denon_avr_x4300h
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.mode_home_theater
- alias: Mode - Home Theater Off
  trigger:
    - platform: state
      entity_id: media_player.denon_avr_x4300h
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.mode_home_theater
