##############################################################
# Garage
##############################################################

- alias: Motion Started in Garage
  trigger:
    platform: state
    entity_id: binary_sensor.garage_motion_sensor
    from: "off"
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.motion_garage
- alias: Motion Ended in Garage
  trigger:
    platform: state
    entity_id: binary_sensor.garage_motion_sensor
    from: "on"
    to: "off"
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.motion_garage


##############################################################
# Garage Stairs
##############################################################

- alias: Motion Started in Garage Stairs
  trigger:
    platform: state
    entity_id: binary_sensor.garage_stairs_multisensor_sensor
    from: "off"
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.motion_garage_stairs
- alias: Motion Ended in Garage Stairs
  trigger:
    platform: state
    entity_id: binary_sensor.garage_stairs_multisensor_sensor
    from: "on"
    to: "off"
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.motion_garage_stairs


##############################################################
# Front Door
##############################################################

# - alias: Motion Started at Front Door
#   trigger:
#     platform: state
#     entity_id: binary_sensor.ring_front_door_motion
#     from: "off"
#     to: "on"
#   action:
#     service: homeassistant.turn_on
#     entity_id: input_boolean.motion_front_door
# - alias: Motion Ended at Front Door Motion Ended
#   trigger:
#     platform: state
#     entity_id: binary_sensor.ring_front_door_motion
#     from: "on"
#     to: "off"
#   action:
#     service: homeassistant.turn_off
#     entity_id: input_boolean.motion_front_door


##############################################################
# Downstairs Hallway
##############################################################

- alias: Motion Started in Downstairs Hallway
  trigger:
    platform: state
    entity_id: binary_sensor.downstairs_hallway_multisensor_sensor
    from: "off"
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.motion_downstairs_hallway
- alias: Motion Ended in Downstairs Hallway
  trigger:
    platform: state
    entity_id: binary_sensor.downstairs_hallway_multisensor_sensor
    from: "on"
    to: "off"
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.motion_downstairs_hallway


##############################################################
# Den Hallway
##############################################################

- alias: Motion Started in Den Hallway
  trigger:
    platform: state
    entity_id: binary_sensor.den_multisensor_sensor
    from: "off"
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.motion_den_hallway
- alias: Motion Ended in Den Hallway
  trigger:
    platform: state
    entity_id: binary_sensor.den_multisensor_sensor
    from: "on"
    to: "off"
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.motion_den_hallway


##############################################################
# Bedroom
##############################################################

- alias: Motion Started in Bedroom
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_closet_trisensor_sensor
    from: "off"
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.motion_bedroom_closet
- alias: Motion Ended in Den
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_closet_trisensor_sensor
    from: "on"
    to: "off"
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.motion_bedroom_closet


##############################################################
# Living Room
##############################################################

- alias: Motion Started in Living Room
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion_sensor
    from: "off"
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.motion_living_room
- alias: Motion Ended in Living Room
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion_sensor
    from: "on"
    to: "off"
    for:
      minutes: 2
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.motion_living_room


##############################################################
# Main Stairs
##############################################################

- alias: Motion Started in Main Stairs
  trigger:
    platform: state
    entity_id: binary_sensor.main_stairs_multisensor_sensor
    from: "off"
    to: "on"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.motion_main_stairs
- alias: Motion Ended in Main Stairs
  trigger:
    platform: state
    entity_id: binary_sensor.main_stairs_multisensor_sensor
    from: "on"
    to: "off"
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.motion_main_stairs


##############################################################
# Upstairs Hallway
##############################################################

- alias: Motion Started in Upstairs Hallway
  trigger:
    platform: state
    entity_id: binary_sensor.upstairs_hallway_motion_sensor
    from: "off"
    to: "on"
  condition:
    condition: state
    entity_id: input_boolean.motion_upstairs_hallway
    state: "off"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.motion_upstairs_hallway
- alias: Motion Ended in Main Stairs
  trigger:
    platform: state
    entity_id: binary_sensor.upstairs_hallway_motion_sensor
    from: "on"
    to: "off"
    for:
      minutes: 2
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.motion_upstairs_hallway
