# Guest Mode #################################################
- alias: Notify of Guest Motion Detected
  trigger:
    - platform: state
      entity_id: input_boolean.mode_guest
      to: 'on'
  action:
    - delay: '00:00:02'
    - service: notify.mobile_app_alexs_iphone
      data_template:
        title: "Condo"
        message: >-
          {%- if is_state("lock.august_smart_lock_pro_front_door", "unlocked") -%}
            Guest Mode has been triggered and the front door was {% if is_state("sensor.august_smart_lock_pro_front_door_access_control", "2") %}manually unlocked.{% elif is_state("sensor.august_smart_lock_pro_front_door_access_control", "4") %}unlocked with the August app.{% elif is_state("sensor.august_smart_lock_pro_front_door_access_control", "6") %}unlocked with the keypad.{% else %}unlocked.{% endif %} Expecting anyone?
          {%- else -%}
            Guest Mode has been triggered and the front door is locked. Cats? Aliens?
          {%- endif %}
        data:
          push:
            thread-id: "ha-condo-group"
            sound: "siren.wav"

- alias: Notify of Guest Mode Ended
  trigger:
    - platform: state
      entity_id: input_boolean.mode_guest
      to: 'off'
  condition:
    - condition: state
      entity_id: group.residents
      state: 'not_home'
  action:
    - service: notify.mobile_app_alexs_iphone
      data_template:
        title: "Condo"
        message: "Motion in guest areas has not been detected for 30 minutes. Guest Mode has been turned off."
        data:
          push:
            thread-id: "ha-condo-group"
            sound: "gamelan.wav"
