##############################################################
# Shell Commands
##############################################################

# Query Cox data usage every 1 hour ##########################
# - alias: Query Cox Data Usage
#   trigger:
#     platform: time
#     hours: '/1'
#     minutes: 00
#     seconds: 00
#   action:
#     service: shell_command.query_cox_data_usagev

# Query suncalc every 1 hour #################################
- alias: Query Suncalc
  trigger:
    platform: time_pattern
    hours: '/1'
    minutes: 00
    seconds: 00
  action:
    service: shell_command.query_suncalc
