##############################################################
# Timed Events
##############################################################
- alias: Sonos Group Restore Morning Settings
  trigger:
    platform: time
    # Military time format. This trigger will fire at 3:00 AM
    at: '03:00:00'
  action:
    - service: script.turn_on
      entity_id: script.sonos_group_morning_settings

- alias: Sonos Kitchen Morning Volume Ramp Up
  trigger:
    - platform: state
      entity_id: sensor.sonos_group_master_state
      to: 'playing'
      for:
        minutes: 2
    - platform: state
      entity_id: sensor.sonos_group_master_state
      to: 'playing'
      for:
        minutes: 4
    - platform: state
      entity_id: sensor.sonos_group_master_state
      to: 'playing'
      for:
        minutes: 6
    - platform: state
      entity_id: sensor.sonos_group_master_state
      to: 'playing'
      for:
        minutes: 8
    - platform: state
      entity_id: sensor.sonos_group_master_state
      to: 'playing'
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: time
            after: '03:00:00'
            before: '09:00:00'
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
          - condition: time
            after: '03:00:00'
            before: '12:00:00'
            weekday:
              - sat
              - sun
      - condition: template
        value_template: '{{ state_attr("media_player.sonos_kitchen", "volume_level") < 0.30 or state_attr("media_player.sonos_bedroom", "volume_level") < 0.30 or state_attr("media_player.sonos_bathroom", "volume_level") < 0.30 }}'
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >-
        {% set players = ["sonos_kitchen", "sonos_bedroom", "sonos_bathroom"] %}
        {% for player in players if state_attr('media_player.' ~ player, 'volume_level') < 0.30 -%}
          {{ 'media_player.' ~ player }}
          {%- if not loop.last -%}
            ,
          {%- endif %}
        {%- endfor %}
      volume_level: >-
        {% set players = ["sonos_kitchen", "sonos_bedroom", "sonos_bathroom"] %}
        {% for player in players if state_attr('media_player.' ~ player, 'volume_level') < 0.30 -%}
          {%- if loop.first -%}
            {{ state_attr('media_player.' ~ player, 'volume_level') + 0.02 }}
          {%- endif %}
        {%- endfor %}

- alias: Sonos Group Restore Default Settings - Weekday
  trigger:
    platform: time
    # Military time format. This trigger will fire at 9:00 AM
    at: '09:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: script.turn_on
      entity_id: script.sonos_group_default_settings

- alias: Sonos Group Restore Default Settings - Weekend
  trigger:
    platform: time
    # Military time format. This trigger will fire at 12:00 PM
    at: '12:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: script.turn_on
      entity_id: script.sonos_group_default_settings


##############################################################
# Speaker Grouping
##############################################################
# Group Master Speaker #######################################
# Sets the input_select based on the master speaker sensor

- alias: Set Sonos Group Master Input Select
  trigger:
    - platform: state
      entity_id: sensor.sonos_group_master
    - platform: homeassistant
      event: start
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ states.sensor.sonos_group_master.state != "" }}'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.master_sonos
        option: >-
          {% set master = states.sensor.sonos_group_master.state %}
          {% if "media_player.sonos_kitchen" in master %}Kitchen
          {% elif "media_player.sonos_living_room" in master%}Living Room
          {% elif "media_player.sonos_rec_room" in master%}Rec Room
          {% elif "media_player.sonos_bedroom" in master%}Bedroom
          {% elif "media_player.sonos_bathroom" in master%}Bathroom
          {% elif "media_player.sonos_den" in master%}Den
          {% endif %}

# Sync Input Booleans to Speaker Status ######################
- alias: Set Sonos Switches On
  trigger:
    - platform: state
      entity_id: sensor.sonos_switches_on
    - platform: homeassistant
      event: start
  condition:
    condition: template
    value_template: '{{ states.sensor.sonos_switches_on.state != "" }}'
  action:
    - service: input_boolean.turn_on
      data_template:
        entity_id: '{{states.sensor.sonos_switches_on.state}}'
- alias: Set Sonos Switches Off
  trigger:
    - platform: state
      entity_id: sensor.sonos_switches_off
    - platform: homeassistant
      event: start
  condition:
    condition: template
    value_template: '{{ states.sensor.sonos_switches_off.state != "" }}'
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: '{{states.sensor.sonos_switches_off.state}}'

# Toggle Speaker State #######################################
- alias: Toggle Sonos Speaker State
  trigger:
    - platform: state
      entity_id: input_boolean.sonos_bathroom
    - platform: state
      entity_id: input_boolean.sonos_bedroom
    - platform: state
      entity_id: input_boolean.sonos_den
    - platform: state
      entity_id: input_boolean.sonos_kitchen
    - platform: state
      entity_id: input_boolean.sonos_living_room
    - platform: state
      entity_id: input_boolean.sonos_rec_room
  condition:
    condition: template
    value_template: >-
      {% set switch  = trigger.to_state.entity_id %}
      {% set speaker = trigger.to_state.entity_id|replace("input_boolean", "media_player") %}
      {% if is_state(switch, "on") %}
        {{ is_state(speaker, "paused") }}
      {% else %}
        {{ is_state(speaker, "playing") }}
      {% endif %}
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {% set switch  = trigger.to_state.entity_id %}
          {% if is_state(switch, "on") %}
            script.sonos_speaker_join_group
          {% else %}
            script.sonos_speaker_unjoin_group
          {% endif %}
        variables:
          speaker: '{{ trigger.to_state.entity_id|replace("input_boolean", "media_player") }}'

##############################################################
# Mode Events
##############################################################
# Toggle Play State ##########################################
- alias: Pause Sonos Speakers When HT Mode Starts
  trigger:
    - platform: state
      entity_id: input_boolean.mode_home_theater
      to: 'on'
  condition:
    - condition: state
      entity_id: sensor.sonos_group_master_state
      state: 'playing'
  action:
    - service: media_player.media_pause
      data_template:
        entity_id: '{{ states.sensor.sonos_group_master.state }}'
