##############################################################
# Homeseer
# https://home-assistant.io/docs/z-wave/device-specific/
# https://gist.github.com/dnschneid/7e36cac10a568a92562880844dbc2874
# Button    scene_id     property_key
# on        1            001
# off       2            002
#
# scene_data
# Action    v1    v2     zwavejs
# single    0     7680   KeyPressed
# hold      2     7740   KeyHeldDown
# release   1     7400   KeyReleased
# double    3     7860   KeyPressed2x
# triple    4     7920   KeyPressed3x
# quad      N/A   7980   KeyPressed4x
# quint     N/A   8040   KeyPressed5x
##############################################################

##############################################################
# Patio
##############################################################

# On #########################################################
- alias: Patio Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 46
        property_key: "001"
  action:
    choose:
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: switch.turn_on
            entity_id: switch.patio_string_lights

# Off ########################################################
- alias: Patio Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 46
        property_key: "002"
  action:
    choose:
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: switch.turn_off
            entity_id: switch.patio_string_lights


##############################################################
# Garage
##############################################################

# On #########################################################
- alias: Garage Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 65
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_lights

# Off ########################################################
- alias: Garage Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 65
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_lights


##############################################################
# Garage Stairs
##############################################################

# On #########################################################
- alias: Garage Stairs Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 35
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_stairs_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_stairs_lights

# Off ########################################################
- alias: Garage Stairs Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 35
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_stairs_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_stairs_lights


##############################################################
# Downstairs Hallway
##############################################################

# On #########################################################
- alias: Downstairs Hallway Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 59
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id:
              - input_boolean.motion_trigger_downstairs_hallway_lights
              - input_boolean.door_trigger_downstairs_hallway_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id:
              - input_boolean.motion_trigger_downstairs_hallway_lights
              - input_boolean.door_trigger_downstairs_hallway_lights

# Off ########################################################
- alias: Downstairs Hallway Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 59
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id:
              - input_boolean.motion_trigger_downstairs_hallway_lights
              - input_boolean.door_trigger_downstairs_hallway_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id:
              - input_boolean.motion_trigger_downstairs_hallway_lights
              - input_boolean.door_trigger_downstairs_hallway_lights


##############################################################
# Main Stairs
##############################################################

# On #########################################################
- alias: Main Stairs Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 48
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: script.turn_on
            entity_id: script.update_lights
            data:
              variables:
                lights:
                  - upstairs_hallway_group
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights

# Off ########################################################
- alias: Main Stairs Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 48
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: light.turn_off
            entity_id: light.upstairs_hallway_group_lights
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights


##############################################################
# Upstairs Hallway
##############################################################

# On #########################################################
- alias: Upstairs Hallway Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 38
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: script.turn_on
            entity_id: script.update_lights
            data:
              variables:
                lights:
                  - upstairs_hallway_group
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights

# Off ########################################################
- alias: Upstairs Hallway Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 38
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: light.turn_off
            entity_id: light.upstairs_hallway_group_lights
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights


##############################################################
# Bedroom Hallway
##############################################################

# On #########################################################
- alias: Bedroom Hallway Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 72
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: script.turn_on
            entity_id: script.update_lights
            data:
              variables:
                lights:
                  - upstairs_hallway_group
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights

# Off ########################################################
- alias: Bedroom Hallway Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 72
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: light.turn_off
            entity_id: light.upstairs_hallway_group_lights
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights


##############################################################
# Den Hallway
##############################################################

# On #########################################################
- alias: Den Hallway Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 60
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_den_hallway_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: script.turn_on
            entity_id: script.update_lights
            data:
              variables:
                lights:
                  - den_cabinets
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_den_hallway_lights

# Off ########################################################
- alias: Den Hallway Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        type: value_notification
        node_id: 60
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_den_hallway_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: light.turn_off
            entity_id: light.den_cabinets
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_den_hallway_lights
