##############################################################
# Homeseer
# https://home-assistant.io/docs/z-wave/device-specific/
# https://gist.github.com/dnschneid/7e36cac10a568a92562880844dbc2874
# Button    property_key
# on        001
# off       002
#
# Inovelli
# https://gist.github.com/mikemsd/f67d1ebc4ef04d040b0b328daebd8520
# Button    property_key
# on        002
# off       001
# config    003
#
# scene_data
# Action    zwavejs
# single    KeyPressed
# hold      KeyHeldDown
# release   KeyReleased
# double    KeyPressed2x
# triple    KeyPressed3x
# quad      KeyPressed4x
# quint     KeyPressed5x
##############################################################

##############################################################
# Patio
##############################################################

# On #########################################################
- alias: Downstairs Patio Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 12
        property_key: "001"
  action:
    choose:
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: switch.turn_on
            entity_id: switch.downstairs_patio_outlet

# Off ########################################################
- alias: Downstairs Patio Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 12
        property_key: "002"
  action:
    choose:
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: switch.turn_off
            entity_id: switch.downstairs_patio_outlet


##############################################################
# Garage
##############################################################

# On #########################################################
- alias: Garage Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 15
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_lights

# Off ########################################################
- alias: Garage Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 15
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_lights


##############################################################
# Garage Stairs
##############################################################

# On #########################################################
- alias: Garage Stairs Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 14
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_stairs_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_stairs_lights

# Off ########################################################
- alias: Garage Stairs Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 14
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_stairs_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_garage_stairs_lights


##############################################################
# Downstairs Hallway
##############################################################

# On #########################################################
- alias: Downstairs Hallway Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 13
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id:
              - input_boolean.motion_trigger_downstairs_hallway_lights
              - input_boolean.door_trigger_downstairs_hallway_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id:
              - input_boolean.motion_trigger_downstairs_hallway_lights
              - input_boolean.door_trigger_downstairs_hallway_lights

# Off ########################################################
- alias: Downstairs Hallway Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 13
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id:
              - input_boolean.motion_trigger_downstairs_hallway_lights
              - input_boolean.door_trigger_downstairs_hallway_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id:
              - input_boolean.motion_trigger_downstairs_hallway_lights
              - input_boolean.door_trigger_downstairs_hallway_lights


##############################################################
# Main Stairs
##############################################################

# On #########################################################
- alias: Main Stairs Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 10
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: script.turn_on
            entity_id: script.update_lights
            data:
              variables:
                lights:
                  - upstairs_hallway_group
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights

# Off ########################################################
- alias: Main Stairs Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 10
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: light.turn_off
            entity_id: light.upstairs_hallway_group
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights


##############################################################
# Upstairs Hallway
##############################################################

# On #########################################################
- alias: Upstairs Hallway Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 9
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: script.turn_on
            entity_id: script.update_lights
            data:
              variables:
                lights:
                  - upstairs_hallway_group
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights

# Off ########################################################
- alias: Upstairs Hallway Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 9
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: light.turn_off
            entity_id:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights


##############################################################
# Bedroom Hallway
##############################################################

# On #########################################################
- alias: Bedroom Hallway Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 6
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: script.turn_on
            entity_id: script.update_lights
            data:
              variables:
                lights:
                  - upstairs_hallway_group
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights

# Off ########################################################
- alias: Bedroom Hallway Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 6
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: light.turn_off
            entity_id: light.upstairs_hallway_group
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_upstairs_hallway_group_lights


##############################################################
# Bedroom
##############################################################

# Sync #######################################################
- alias: Bedroom Dimmer Lights Sync
  trigger:
    - id: "brightness"
      platform: state
      entity_id:
        - light.bedroom
        - light.bedroom_switch
      attribute: brightness
    - id: "off"
      platform: state
      entity_id:
        - light.bedroom
        - light.bedroom_switch
      to: "off"
  action:
    choose:
      - conditions:
          - condition: trigger
            id: "brightness"
        sequence:
          - parallel:
              - service: light.turn_on
                entity_id: light.bedroom_1
                data:
                  brightness: "{{ state_attr(trigger.entity_id, 'brightness') | int }}"
              - service: light.turn_on
                entity_id: light.bedroom_2
                data:
                  brightness: "{{ state_attr(trigger.entity_id, 'brightness') | int }}"
              - service: light.turn_on
                data:
                  brightness: "{{ state_attr(trigger.entity_id, 'brightness') | int }}"
                entity_id: light.bedroom_switch
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - service: light.turn_off
            entity_id: 
                - light.bedroom
                - light.bedroom_switch
  mode: restart

# Config #####################################################
- alias: Bedroom Dimmer Config Scene Toggle
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 34
        property_key: "003"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_select.select_next
            data:
              cycle: true
            target:
              entity_id: input_select.bedroom_scene_toggle              
          - service: script.turn_on
            target:
              entity_id: '{{ states("input_select.bedroom_scene_toggle") }}'
            data:
              variables:
                seconds: 1
  mode: queued


##############################################################
# Den Hallway
##############################################################

# On #########################################################
- alias: Den Hallway Physical Switch On
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 5
        property_key: "001"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_den_hallway_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: script.turn_on
            entity_id: script.update_lights
            data:
              variables:
                lights:
                  - den_cabinets
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_den_hallway_lights

# Off ########################################################
- alias: Den Hallway Physical Switch Off
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        type: value_notification
        node_id: 5
        property_key: "002"
  action:
    choose:
      # Single Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_den_hallway_lights
      # Double Tap
      - conditions:
          - '{{ trigger.event.data.value == "KeyPressed2x" }}'
        sequence:
          - service: light.turn_off
            entity_id: light.den_cabinets
      # Hold
      - conditions:
          - '{{ trigger.event.data.value == "KeyHeldDown" }}'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.motion_trigger_den_hallway_lights
