##############################################################
# Homeseer
# https://home-assistant.io/docs/z-wave/device-specific/
##############################################################

##############################################################
# Kitchen
##############################################################

# On - Single ################################################
- alias: Kitchen Physical Switch On Single
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_kitchen_switch
        scene_id: 1
        scene_data: 0
  action: 
  - service: switch.turn_on
    entity_id: switch.kitchen_lights

# Off - Single ###############################################
- alias: Kitchen Physical Switch Off Single
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_kitchen_switch
        scene_id: 2
        scene_data: 0
  action: 
  - service: switch.turn_off
    entity_id: switch.kitchen_lights

# On - Double ################################################
- alias: Kitchen Physical Switch On Double
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_kitchen_switch
        scene_id: 1
        scene_data: 3
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_kitchen_bright

# Off - Double ###############################################
- alias: Kitchen Physical Switch Off Double
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_kitchen_switch
        scene_id: 2
        scene_data: 3
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_kitchen_dim

# On - Triple ################################################
- alias: Kitchen Physical Switch On Triple
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_kitchen_switch
        scene_id: 1
        scene_data: 4
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_kitchen_prep

# Off - Hold #################################################
- alias: Kitchen Physical Switch Off Hold
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_kitchen_switch
        scene_id: 2
        scene_data: 2
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_goodbye


##############################################################
# Bathroom
##############################################################

# On - Single ################################################
- alias: Bathroom Physical Switch On Single
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_bathroom_switch
        scene_id: 1
        scene_data: 0
  action: 
  - service: switch.turn_on
    entity_id: switch.bathroom_lights

# Off - Single ###############################################
- alias: Bathroom Physical Switch Off Single
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_bathroom_switch
        scene_id: 2
        scene_data: 0
  action: 
  - service: switch.turn_off
    entity_id: switch.bathroom_lights

# On - Double ################################################
- alias: Bathroom Physical Switch On Double
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_bathroom_switch
        scene_id: 1
        scene_data: 3
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_bathroom_bright

# Off - Double ###############################################
- alias: Bathroom Physical Switch Off Double
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_bathroom_switch
        scene_id: 2
        scene_data: 3
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_bathroom_dim


##############################################################
# Bedroom
##############################################################

# On - Single ################################################
- alias: Bedroom Physical Switch On Single
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_bedroom_switch
        scene_id: 1
        scene_data: 0
  action: 
  - service: switch.turn_on
    entity_id: switch.bedroom_lights

# Off - Single ###############################################
- alias: Bedroom Physical Switch Off Single
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_bedroom_switch
        scene_id: 2
        scene_data: 0
  action: 
  - service: switch.turn_off
    entity_id: switch.bedroom_lights

# On - Double ################################################
- alias: Bedroom Physical Switch On Double
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_bedroom_switch
        scene_id: 1
        scene_data: 3
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_bedroom_bright

# Off - Double ###############################################
- alias: Bedroom Physical Switch Off Double
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_bedroom_switch
        scene_id: 2
        scene_data: 3
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_bedroom_dim

# On - Hold ##################################################
- alias: Bedroom Physical Switch On Hold
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_bedroom_switch
        scene_id: 1
        scene_data: 2
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_bedroom_ambient

# Off - Hold #################################################
- alias: Bedroom Physical Switch Off Hold
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_bedroom_switch
        scene_id: 2
        scene_data: 2
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_bedtime


##############################################################
# Living Room
##############################################################

# On - Single ################################################
- alias: Living Room Physical Switch On Single
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_living_room_switch
        scene_id: 1
        scene_data: 0
  action: 
  - service: switch.turn_on
    entity_id: switch.living_room_lights

# Off - Single ###############################################
- alias: Living Room Physical Switch Off Single
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_living_room_switch
        scene_id: 2
        scene_data: 0
  action: 
  - service: switch.turn_off
    entity_id: switch.living_room_lights

# On - Double ################################################
- alias: Living Room Physical Switch On Double
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_living_room_switch
        scene_id: 1
        scene_data: 3
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_living_room_bright

# Off - Double ###############################################
- alias: Living Room Physical Switch Off Double
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_living_room_switch
        scene_id: 2
        scene_data: 3
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_living_room_dim

# On - Triple ################################################
- alias: Living Room Physical Switch On Triple
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_living_room_switch
        scene_id: 1
        scene_data: 4
  action: 
  - service: shell_command.hyperion_mood_blobs_blue

# Off - Triple ###############################################
- alias: Living Room Physical Switch Off Triple
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_living_room_switch
        scene_id: 2
        scene_data: 4
  action: 
  - service: shell_command.hyperion_off

# On - Hold ##################################################
- alias: Living Room Physical Switch On Hold
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_living_room_switch
        scene_id: 1
        scene_data: 2
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_living_room_ambient

# Off - Hold #################################################
- alias: Living Room Physical Switch Off Hold
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.homeseer_living_room_switch
        scene_id: 2
        scene_data: 2
  action: 
  - service: script.turn_on
    entity_id: script.scene_select_goodbye