##############################################################
# Cycle Stale Air
##############################################################
- alias: Cycle Stale Air When Away
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'not_home'
      for:
        hours: 2
    - platform: state
      entity_id: group.residents
      to: 'not_home'
      for:
        hours: 4
    - platform: state
      entity_id: group.residents
      to: 'not_home'
      for:
        hours: 6
  condition:
    - condition: state
      entity_id: group.residents
      state: 'not_home'
    - condition: state
      entity_id:
        - input_boolean.mode_guest
        - group.all_windows
      state: 'off'
    - '{{ state_attr("climate.downstairs", "preset_mode") | lower == "away and eco" or state_attr("climate.downstairs", "preset_mode") | lower == "eco" }}'
    - '{{ state_attr("climate.upstairs", "preset_mode") | lower == "away and eco" or state_attr("climate.upstairs", "preset_mode") | lower == "eco" }}'
  action:
    - service: script.turn_on
      entity_id: script.nest_circulate_stale_air
      data:
        variables:
          minutes: 15
- alias: End Cycle Stale Air Upon Return
  trigger:
    - platform: state
      entity_id: group.residents
      to: 'home'
    - platform: state
      entity_id: input_boolean.mode_guest
      to: 'on'
  condition:
    - condition: state
      entity_id: script.nest_circulate_stale_air
      state: 'on'
  action:
    - service: script.turn_off
      entity_id: script.nest_circulate_stale_air
    - service: climate.set_fan_mode
      entity_id:
        - climate.downstairs
        - climate.upstairs
      data:
        fan_mode: 'auto'
