##############################################################
# Downstairs Windows
##############################################################
# Checks to make sure it's the first thermostate to switch mode
# or that it's triggering before All Windows triggers
- alias: Set Downstairs Thermostat to ECO When Windows Open
  trigger:
    - platform: state
      entity_id: group.downstairs_windows
      from: 'off'
      to: 'on'
      for:
        seconds: 30
    - platform: event
      event_type: event_check_downstairs_windows
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: group.residents
            state: 'home'
          - condition: state
            entity_id: input_boolean.mode_guest
            state: 'on'
      - condition: state
        entity_id: group.all_windows
        state: 'on'
      - '{{ state_attr("climate.downstairs", "preset_mode") | lower != "eco" and states("climate.downstairs") | lower != "off" }}'
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.downstairs
        hvac_mode: 'auto'
    - service: climate.set_preset_mode
      data:
        entity_id: climate.downstairs
        preset_mode: 'eco'
    - delay: '00:05:00'
    - event: event_check_upstairs_windows


##############################################################
# Upstairs Windows
##############################################################
# Checks to make sure it's the first thermostate to switch mode
# or that it's triggering before All Windows triggers
- alias: Set Upstairs Thermostat to ECO When Windows Open
  trigger:
    - platform: state
      entity_id: group.upstairs_windows
      from: 'off'
      to: 'on'
      for:
        seconds: 30
    - platform: event
      event_type: event_check_upstairs_windows
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: group.residents
            state: 'home'
          - condition: state
            entity_id: input_boolean.mode_guest
            state: 'on'
      - condition: state
        entity_id: group.all_windows
        state: 'on'
      - '{{ state_attr("climate.upstairs", "preset_mode") | lower != "eco" and states("climate.upstairs") | lower != "off" }}'
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.upstairs
        hvac_mode: 'auto'
    - service: climate.set_preset_mode
      data:
        entity_id: climate.upstairs
        preset_mode: 'eco'
    - delay: '00:05:00'
    - event: event_check_downstairs_windows


##############################################################
# Restore Nest Mode
##############################################################
# Checks to make sure at least one thermostat is not in eco mode
- alias: Restore All Thermostats When Windows Close
  trigger:
    - platform: state
      entity_id: group.all_windows
      from: 'on'
      to: 'off'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.residents
        state: 'home'
      - condition: state
        entity_id: input_boolean.mode_guest
        state: 'on'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.downstairs
        preset_mode: 'none'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.downstairs
        hvac_mode: '{{ states("sensor.climate_downstairs_restore_mode") }}'
    - service: climate.set_preset_mode
      data:
        entity_id: climate.upstairs
        preset_mode: 'none'
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.upstairs
        hvac_mode: '{{ states("sensor.climate_upstairs_restore_mode") }}'
