security:
  template: base
  state:
    - value: "open"
      styles:
        card:
          - background: var(--card-on-background-color)
        icon:
          - color: var(--card-on-icon-color)
        name:
          - color: var(--card-on-text-color)
        state:
          - color: var(--card-on-text-color)
    - value: "unlocked"
      styles:
        card:
          - background: var(--card-on-background-color)
        icon:
          - color: var(--card-on-icon-color)
        name:
          - color: var(--card-on-text-color)
        state:
          - color: var(--card-on-text-color)
    - value: "closed"
      styles:
        card:
          - background: var(--card-off-background-color)
        icon:
          - color: var(--card-off-icon-color)
        name:
          - color: var(--card-off-text-color)
        state:
          - color: var(--card-off-text-color)
    - value: "locked"
      styles:
        card:
          - background: '[[[ if(variables.door == "on") return "var(--card-on-background-color)"; else return "var(--card-off-background-color)" ]]]'
        icon:
          - color: '[[[ if(variables.door == "on") return "var(--card-on-icon-color)"; else return "var(--card-off-icon-color)" ]]]'
        name:
          - color: '[[[ if(variables.door == "on") return "var(--card-on-text-color)"; else return "var(--card-off-text-color)" ]]]'
        state:
          - color: '[[[ if(variables.door == "on") return "var(--card-on-text-color)"; else return "var(--card-off-text-color)" ]]]'
